const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const { randomUUID, createHash } = require("node:crypto");
const { execFile, spawn } = require("node:child_process");
const { promisify } = require("node:util");
const { writePrivateFileAtomic } = require("./atomic-file.cjs");
const { isolatedEnvironment, launchSpec } = require("./codex-copy-runner.cjs");
const runFile = promisify(execFile);
const ID = /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/;
const digest = data => createHash("sha256").update(data).digest("hex");
const quote = value => `'${value.replaceAll("'", `'"'"'`)}'`;
const fileHash = file => digest(fs.readFileSync(file));

function plain(file, directory = false) {
  const stat = fs.lstatSync(file);
  if (stat.isSymbolicLink() || (directory ? !stat.isDirectory() : !stat.isFile())) throw new Error("SM_COPY_UNSAFE_PATH");
  return stat;
}
function privateDir(directory) {
  fs.mkdirSync(directory, { recursive: true, mode: 0o700 }); plain(directory, true);
  if (process.platform !== "win32") fs.chmodSync(directory, 0o700);
}
function executable(file) {
  try { return fs.statSync(file).isFile() && (process.platform === "win32" || (fs.accessSync(file, fs.constants.X_OK), true)); }
  catch { return false; }
}
function detectCodex(env = process.env, platform = process.platform) {
  const candidates = [env.CODEX_CLI_PATH,
    ...(platform === "linux" ? ["/usr/lib/chatgpt/resources/codex", "/usr/lib/codex/resources/codex"] : []),
    ...(platform === "darwin" ? ["/Applications/ChatGPT.app/Contents/Resources/codex", "/Applications/Codex.app/Contents/Resources/codex"] : []),
    ...["ChatGPT", "Codex"].map(name => env.LOCALAPPDATA ? path.join(env.LOCALAPPDATA, "Programs", name, "resources", "codex.exe") : null),
    ...(env.PATH || "").split(path.delimiter).filter(Boolean).map(dir => path.join(dir, platform === "win32" ? "codex.exe" : "codex")),
  ].filter(file => typeof file === "string" && path.isAbsolute(file));
  const codexExecutable = candidates.find(executable);
  if (!codexExecutable) return { codexExecutable: null, desktopExecutable: null };
  const codex = fs.realpathSync(codexExecutable);
  const base = path.dirname(path.dirname(codex));
  const desktopExecutable = (platform === "darwin" ? [path.join(base, "MacOS", "ChatGPT"), path.join(base, "MacOS", "Codex")]
    : [path.join(base, platform === "win32" ? "ChatGPT.exe" : "ChatGPT"), path.join(base, platform === "win32" ? "Codex.exe" : "Codex")]).find(executable) || null;
  return { codexExecutable: codex, desktopExecutable };
}

function copyConfig({ mode, catalog, endpoint, interruptHook = "" }) {
  const common = ['# Generated by Star Moon. Credentials and tasks belong only to this CODEX_HOME.',
    'cli_auth_credentials_store = "file"', 'mcp_oauth_credentials_store = "file"',
    'approval_policy = "on-request"', 'sandbox_mode = "workspace-write"'];
  if (mode === "native") return common.join("\n") + "\n";
  const models = catalog?.models;
  if (!Array.isArray(models) || !models.length || models.some(model => typeof model.slug !== "string" || !model.slug.startsWith("chatgpt-web/"))) throw new Error("SM_COPY_INVALID_CATALOG");
  const url = new URL(endpoint);
  if (url.protocol !== "http:" || url.hostname !== "127.0.0.1" || !url.port || url.username || url.password || url.search || url.hash || url.pathname !== "/v1") throw new Error("SM_COPY_UNSAFE_ENDPOINT");
  const selected = models.find(model => model.slug === "chatgpt-web/high") || models[0];
  return [...common, `model = ${JSON.stringify(selected.slug)}`, `model_reasoning_effort = ${JSON.stringify(selected.default_reasoning_level)}`,
    'model_catalog_json = "models.json"', 'model_provider = "star_moon_web"',
    '', '[model_providers.star_moon_web]', 'name = "Star Moon Web (local)"', `base_url = ${JSON.stringify(url.toString())}`,
    'wire_api = "responses"', 'requires_openai_auth = false', 'supports_websockets = false', '',
    '[features]', 'multi_agent = true', 'multi_agent_v2 = false', '', '[agents]', 'max_depth = 2', '', interruptHook, ''].join("\n");
}

class CodexCopies {
  constructor({ root, buildCatalog, engine, logger = { info() {}, warn() {} }, detect = detectCodex, run = runFile, launch = spawn }) {
    this.root = path.resolve(root); this.buildCatalog = buildCatalog; this.engine = engine;
    this.logger = logger; this.detect = detect; this.run = run; this.launch = launch; this.busy = false; this.children = new Map();
  }
  directory(id) { if (!ID.test(id)) throw new Error("SM_COPY_INVALID_ID"); return path.join(this.root, id); }
  ensureRoot() { plain(path.dirname(this.root), true); privateDir(this.root); }
  read(id) {
    plain(this.root, true); const root = this.directory(id); plain(root, true);
    const file = path.join(root, "manifest.json");
    if (plain(file).size > 65536) throw new Error("SM_COPY_INVALID_MANIFEST");
    const data = JSON.parse(fs.readFileSync(file, "utf8"));
    if (data.version !== 1 || data.id !== id || !["native", "web"].includes(data.mode) || typeof data.name !== "string" || !data.hashes) throw new Error("SM_COPY_INVALID_MANIFEST");
    for (const directory of ["home", "desktop", "workspace"]) plain(path.join(root, directory), true);
    return { root, data };
  }
  issues(root, data) {
    const issues = [];
    for (const name of ["home/config.toml", "run.cjs", "codex-copy-validator.cjs", ...(data.mode === "web" ? ["home/models.json"] : [])]) {
      try { plain(path.join(root, name)); if (name !== "home/config.toml" && fileHash(path.join(root, name)) !== data.hashes[name]) issues.push(`modified:${name}`); }
      catch { issues.push(`missing-or-unsafe:${name}`); }
    }
    if (!executable(data.codexExecutable)) issues.push("codex-not-found");
    for (const name of ["auth.json", ".credentials.json"]) {
      const file = path.join(root, "home", name);
      if (fs.existsSync(file)) {
        try { const stat = plain(file); if (process.platform !== "win32" && (stat.mode & 0o077)) issues.push("credential-file-permissions"); }
        catch { issues.push("unsafe-credential-file"); }
      }
    }
    const known = this.detect();
    if (known.codexExecutable !== data.codexExecutable || known.desktopExecutable !== data.desktopExecutable) issues.push("installed-program-changed");
    return issues;
  }
  summary(id) {
    const { root, data } = this.read(id), issues = this.issues(root, data);
    const child = this.children.get(id), running = Boolean(child && child.exitCode === null && child.signalCode === null);
    return { id, name: data.name, mode: data.mode, archived: Boolean(data.archived), createdAt: data.createdAt,
      home: path.join(root, "home"), desktopData: path.join(root, "desktop"), cliLauncher: path.join(root, process.platform === "win32" ? "start-cli.cmd" : "start-cli.command"),
      codexVersion: data.codexVersion, desktopAvailable: Boolean(data.desktopExecutable && executable(data.desktopExecutable)),
      status: issues.length ? "needs-attention" : running ? "running" : "created", issues,
      customizedConfig: (() => { try { return fileHash(path.join(root, "home/config.toml")) !== data.hashes["home/config.toml"]; } catch { return false; } })(),
      verification: data.verification || null, pid: running ? child.pid : null };
  }
  list() {
    const runtime = this.detect();
    if (!fs.existsSync(this.root)) return { runtime, copies: [] };
    plain(this.root, true);
    const ids = fs.readdirSync(this.root).filter(id => ID.test(id));
    if (ids.length > 32) throw new Error("SM_COPY_LIMIT");
    return { runtime, copies: ids.map(id => { try { return this.summary(id); } catch { return { id, name: id, status: "needs-attention", issues: ["invalid-manifest"] }; } }) };
  }
  async create(input) {
    if (this.busy) throw new Error("SM_COPY_BUSY");
    if (!input || !["native", "web"].includes(input.mode) || typeof input.name !== "string" || !input.name.trim() || input.name.trim().length > 60 || /[\x00-\x1f\x7f]/.test(input.name)) throw new Error("SM_COPY_INVALID_INPUT");
    this.busy = true; let staging;
    try {
      this.ensureRoot();
      if (this.list().copies.length >= 32) throw new Error("SM_COPY_LIMIT");
      const runtime = this.detect();
      if (!runtime.codexExecutable) throw new Error("SM_COPY_CODEX_NOT_FOUND");
      const id = randomUUID(), destination = this.directory(id);
      staging = fs.mkdtempSync(path.join(this.root, ".creating-"));
      for (const directory of ["home", "desktop", "workspace"]) privateDir(path.join(staging, directory));
      const env = isolatedEnvironment(path.join(staging, "home"), path.join(staging, "desktop"));
      const options = { env, cwd: path.join(staging, "workspace"), encoding: "utf8", timeout: 15000, maxBuffer: 8 * 1024 * 1024, windowsHide: true };
      const version = (await this.run(runtime.codexExecutable, ["--version"], options)).stdout.trim();
      if (!/^codex-cli \d+\.\d+\.\d+(?:[^\r\n]{0,80})?$/.test(version)) throw new Error("SM_COPY_UNSUPPORTED_CODEX");
      let catalog, endpoint, interruptHook;
      if (input.mode === "web") {
        const bundled = await this.run(runtime.codexExecutable, ["debug", "models", "--bundled"], options);
        const templatePath = path.join(staging, "native-template.json");
        writePrivateFileAtomic(templatePath, bundled.stdout);
        const built = await this.buildCatalog(templatePath, path.join(destination, "home", "config.toml"));
        catalog = built.catalog; endpoint = built.endpoint; interruptHook = built.interruptHook;
        writePrivateFileAtomic(path.join(staging, "home", "models.json"), JSON.stringify(catalog));
        fs.unlinkSync(templatePath);
      }
      writePrivateFileAtomic(path.join(staging, "home", "config.toml"), copyConfig({ mode: input.mode, catalog, endpoint, interruptHook }));
      fs.copyFileSync(path.join(__dirname, "codex-copy-runner.cjs"), path.join(staging, "run.cjs"));
      fs.copyFileSync(path.join(__dirname, "codex-copy-validator.cjs"), path.join(staging, "codex-copy-validator.cjs"));
      const runner = path.join(destination, "run.cjs");
      if (process.platform === "win32") {
        const cmdQuote = value => `"${value.replaceAll("%", "%%")}"`;
        if ([this.engine, runner].some(value => /[\r\n"]/.test(value))) throw new Error("SM_COPY_UNSAFE_PATH");
        writePrivateFileAtomic(path.join(staging, "start-cli.cmd"), `@echo off\r\n${cmdQuote(this.engine)} ${cmdQuote(runner)} %*\r\n`);
      } else {
        writePrivateFileAtomic(path.join(staging, "start-cli.command"), `#!/bin/sh\nexec ${quote(this.engine)} ${quote(runner)} "$@"\n`);
        fs.chmodSync(path.join(staging, "start-cli.command"), 0o700);
      }
      const parsed = JSON.parse((await this.run(runtime.codexExecutable, ["debug", "models", ...(input.mode === "native" ? ["--bundled"] : [])], options)).stdout);
      if (!Array.isArray(parsed.models) || (input.mode === "web" && !parsed.models.some(model => catalog.models.some(expected => expected.slug === model.slug)))) throw new Error("SM_COPY_CATALOG_NOT_LOADED");
      const managed = ["home/config.toml", "run.cjs", "codex-copy-validator.cjs", ...(input.mode === "web" ? ["home/models.json"] : [])];
      const manifest = { version: 1, id, name: input.name.trim(), mode: input.mode, createdAt: new Date().toISOString(),
        ...runtime, codexVersion: version, endpoint, archived: false,
        hashes: Object.fromEntries(managed.map(name => [name, fileHash(path.join(staging, name))])),
        verification: { kind: "local-catalog-loaded", at: new Date().toISOString(), modelCalls: 0, credentialsCopied: false } };
      writePrivateFileAtomic(path.join(staging, "manifest.json"), JSON.stringify(manifest, null, 2));
      fs.renameSync(staging, destination); staging = null;
      this.logger.info("codex_copy.created", { id, mode: input.mode });
      return this.summary(id);
    } catch (error) {
      if (/^SM_COPY_/.test(error.message)) throw error;
      throw new Error("SM_COPY_CREATE_FAILED: No existing profile was changed; check the installed Codex version.");
    } finally {
      if (staging) fs.rmSync(staging, { recursive: true, force: true });
      this.busy = false;
    }
  }
  async inspect(id) {
    const summary = this.summary(id);
    if (summary.issues.length) return summary;
    const { root, data } = this.read(id);
    const isolation = await this.checkConfig(root, data);
    if (!isolation.ok) return { ...summary, status: "needs-attention", issues: isolation.issues };
    const result = await this.run(data.codexExecutable, ["debug", "models", ...(data.mode === "native" ? ["--bundled"] : [])], { cwd: path.join(root, "workspace"), env: isolatedEnvironment(path.join(root, "home"), path.join(root, "desktop")), encoding: "utf8", timeout: 15000, maxBuffer: 8 * 1024 * 1024, windowsHide: true });
    if (!Array.isArray(JSON.parse(result.stdout).models)) throw new Error("SM_COPY_CATALOG_NOT_LOADED");
    let login = "not-verified";
    try {
      const result = await this.run(data.codexExecutable, ["login", "status"], { cwd: path.join(root, "workspace"), env: isolatedEnvironment(path.join(root, "home"), path.join(root, "desktop")), encoding: "utf8", timeout: 8000, maxBuffer: 65536, windowsHide: true });
      const status = `${result.stdout || ""}\n${result.stderr || ""}`;
      login = /Logged in using ChatGPT/i.test(status) ? "chatgpt" : /Logged in using an API key/i.test(status) ? "api-key" : "not-verified";
    } catch (error) { if (/Not logged in/i.test(`${error.stdout || ""}\n${error.stderr || ""}`)) login = "not-logged-in"; }
    return { ...summary, login, verification: { kind: "local-catalog-loaded", at: new Date().toISOString(), modelCalls: 0, credentialsCopied: false } };
  }
  async checkConfig(root, data) {
    const result = await this.run(this.engine, [path.join(root, "codex-copy-validator.cjs"), path.join(root, "home", "config.toml"), data.mode, data.endpoint || ""], {
      cwd: root, env: isolatedEnvironment(path.join(root, "home"), path.join(root, "desktop")), encoding: "utf8", timeout: 8000, maxBuffer: 65536, windowsHide: true,
    });
    const checked = JSON.parse(result.stdout);
    if (typeof checked.ok !== "boolean" || !Array.isArray(checked.issues)) throw new Error("SM_COPY_CONFIG_REQUIRES_REVIEW");
    return checked;
  }
  async open(id) {
    const summary = this.summary(id);
    if (summary.archived || summary.issues.length) throw new Error("SM_COPY_REQUIRES_REVIEW");
    if (summary.status === "running") return summary;
    const { root, data } = this.read(id), spec = launchSpec(root, data, true);
    if (!(await this.checkConfig(root, data)).ok) throw new Error("SM_COPY_CONFIG_REQUIRES_REVIEW");
    const child = this.launch(spec.executable, spec.args, { env: spec.env, cwd: spec.cwd, detached: true, stdio: "ignore", windowsHide: false });
    this.children.set(id, child);
    await new Promise((resolve, reject) => { child.once("spawn", resolve); child.once("error", () => reject(new Error("SM_COPY_LAUNCH_FAILED"))); });
    child.unref();
    await new Promise(resolve => setTimeout(resolve, 1500));
    if (child.exitCode !== null || child.signalCode !== null) throw new Error("SM_COPY_DESKTOP_EXITED: Use the CLI launcher; desktop isolation could not be confirmed.");
    return this.summary(id);
  }
  archive(id, archived) {
    if (typeof archived !== "boolean") throw new Error("SM_COPY_INVALID_INPUT");
    const { root, data } = this.read(id);
    writePrivateFileAtomic(path.join(root, "manifest.json"), JSON.stringify({ ...data, archived }, null, 2));
    return this.summary(id); // Entry only: no config, credentials or task data is deleted.
  }
}

module.exports = { CodexCopies, detectCodex, copyConfig };
