const { contextBridge, ipcRenderer } = require("electron");

function subscription(channel, listener) {
  const wrapped = (_event, value) => listener(value);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
}

contextBridge.exposeInMainWorld("codexWebLauncher", {
  codexCopies: () => ipcRenderer.invoke("launcher:codex-copies-list"),
  createCodexCopy: input => ipcRenderer.invoke("launcher:codex-copies-create", input),
  inspectCodexCopy: id => ipcRenderer.invoke("launcher:codex-copies-inspect", id),
  openCodexCopy: id => ipcRenderer.invoke("launcher:codex-copies-open", id),
  archiveCodexCopy: (id, archived) => ipcRenderer.invoke("launcher:codex-copies-archive", id, archived),
  openCodexCopyFolder: id => ipcRenderer.invoke("launcher:codex-copies-folder", id),
  startCodexCopyLogin: id => ipcRenderer.invoke("launcher:codex-copy-login-start", id),
  verifyCodexCopyLogin: id => ipcRenderer.invoke("launcher:codex-copy-login-verify", id),
  codexCopyLoginStatus: () => ipcRenderer.invoke("launcher:codex-copy-login-status"),
  cancelCodexCopyLogin: () => ipcRenderer.invoke("launcher:codex-copy-login-cancel"),
  setCodexCopyLoginBounds: bounds => ipcRenderer.invoke("launcher:codex-copy-login-bounds", bounds),
  onCodexCopyLoginChanged: listener => subscription("launcher:codex-copy-login-changed", listener),
  snapshot: () => ipcRenderer.invoke("launcher:snapshot"),
  setLanguage: (language) => ipcRenderer.invoke("launcher:set-language", language),
  setTheme: (theme) => ipcRenderer.invoke("launcher:set-theme", theme),
  completeOnboarding: (language, browserInteractionMode) => ipcRenderer.invoke(
    "launcher:complete-onboarding",
    language,
    browserInteractionMode,
  ),
  reopenOnboarding: () => ipcRenderer.invoke("launcher:reopen-onboarding"),
  openExternal: (url) => ipcRenderer.invoke("launcher:open-external", url),
  setBrowserBounds: (bounds) => ipcRenderer.invoke("launcher:browser-bounds", bounds),
  setBrowserSurfaceActive: (active) => ipcRenderer.invoke("launcher:browser-surface-active", active),
  showBrowser: () => ipcRenderer.invoke("launcher:browser-show"),
  hideBrowser: () => ipcRenderer.invoke("launcher:browser-hide"),
  navigateBrowser: (action) => ipcRenderer.invoke("launcher:browser-navigate", action),
  zoomBrowser: (action) => ipcRenderer.invoke("launcher:browser-zoom", action),
  selectBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-select", tabId),
  closeBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-close", tabId),
  copyManualPrompt: (tabId) => ipcRenderer.invoke("launcher:manual-prompt-copy", tabId),
  confirmManualSent: (tabId) => ipcRenderer.invoke("launcher:manual-prompt-sent", tabId),
  openLogin: () => ipcRenderer.invoke("launcher:browser-login"),
  cancelLogin: () => ipcRenderer.invoke("launcher:browser-login-cancel"),
  reloadLogin: () => ipcRenderer.invoke("launcher:browser-login-reload"),
  openPasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login"),
  continuePasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login-continue"),
  cancelPasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login-cancel"),
  pauseGuidedSetup: stage => ipcRenderer.invoke("launcher:guided-setup-pause", stage),
  resumeGuidedSetup: () => ipcRenderer.invoke("launcher:guided-setup-resume"),
  rememberGuidedSetupPage: stage => ipcRenderer.invoke("launcher:guided-setup-page", stage),
  quitLauncher: () => ipcRenderer.invoke("launcher:quit"),
  logoutChatGpt: () => ipcRenderer.invoke("launcher:browser-logout"),
  dismissSessionReminder: () => ipcRenderer.invoke("launcher:session-reminder-dismiss"),
  smokeTest: () => ipcRenderer.invoke("launcher:browser-smoke"),
  verifyMcp: () => ipcRenderer.invoke("launcher:mcp-verify"),
  doctor: () => ipcRenderer.invoke("launcher:doctor"),
  cockpitStatus: () => ipcRenderer.invoke("launcher:cockpit-status"),
  cockpitConfigure: input => ipcRenderer.invoke("launcher:cockpit-configure", input),
  cockpitProbe: () => ipcRenderer.invoke("launcher:cockpit-probe"),
  cockpitRollback: () => ipcRenderer.invoke("launcher:cockpit-rollback"),
  cockpitEvidence: limit => ipcRenderer.invoke("launcher:cockpit-evidence", { limit }),
  cockpitKeyFile: () => ipcRenderer.invoke("launcher:cockpit-key-file"),
  cockpitClientKeyCopy: () => ipcRenderer.invoke("launcher:cockpit-client-key-copy"),
  catalogStatus: () => ipcRenderer.invoke("launcher:catalog-status"),
  deferCatalogCheck: () => ipcRenderer.invoke("launcher:catalog-defer"),
  finishGuidedSetup: () => ipcRenderer.invoke("launcher:finish-guided-setup"),
  agentDockRead: () => ipcRenderer.invoke("launcher:agentdock-read"),
  agentDockConfigure: input => ipcRenderer.invoke("launcher:agentdock-configure", input),
  agentDockInspect: () => ipcRenderer.invoke("launcher:agentdock-inspect"),
  agentDockLogin: () => ipcRenderer.invoke("launcher:agentdock-login"),
  openAgentDockWebSetup: () => ipcRenderer.invoke("launcher:agentdock-web-setup"),
  onAgentDockChanged: listener => subscription("launcher:agentdock-changed", listener),
  createMoonLetter: consent => ipcRenderer.invoke("launcher:moon-letter-create", consent),
  moonLetterStatus: () => ipcRenderer.invoke("launcher:moon-letter-status"),
  openMoonLetterControl: () => ipcRenderer.invoke("launcher:moon-letter-open"),
  stopMoonLetter: () => ipcRenderer.invoke("launcher:moon-letter-stop"),
  cancelTurns: () => ipcRenderer.invoke("launcher:cancel-turns"),
  uninstallIntegration: () => ipcRenderer.invoke("launcher:uninstall-integration"),
  setupCore: () => ipcRenderer.invoke("launcher:setup-core"),
  setupMcp: (input) => ipcRenderer.invoke("launcher:setup-mcp", input),
  setMcpStep: (step) => ipcRenderer.invoke("launcher:set-mcp-step", step),
  setAutostart: (enabled) => ipcRenderer.invoke("launcher:autostart", enabled),
  setBiggerContext: (enabled) => ipcRenderer.invoke("launcher:bigger-context", enabled),
  setZeroRiskPro: (enabled) => ipcRenderer.invoke("launcher:zero-risk-pro", enabled),
  setBrowserInteractionMode: (mode) => ipcRenderer.invoke("launcher:browser-interaction-mode", mode),
  setPreference: (key, value) => ipcRenderer.invoke("launcher:set-preference", key, value),
  setSidebarState: (state) => ipcRenderer.invoke("launcher:sidebar-state", state),
  logs: (limit) => ipcRenderer.invoke("launcher:logs", limit),
  exportLogs: () => ipcRenderer.invoke("launcher:export-logs"),
  openDevTools: () => ipcRenderer.invoke("launcher:open-devtools"),
  installUpdate: () => ipcRenderer.invoke("launcher:update-install"),
  windowState: () => ipcRenderer.invoke("launcher:window-state"),
  windowControl: (action) => ipcRenderer.send("launcher:window-control", action),
  onWindowStateChanged: (listener) => subscription("launcher:window-state-changed", listener),
  onStateChanged: (listener) => subscription("launcher:state-changed", listener),
  onBrowserState: (listener) => subscription("launcher:browser-state", listener),
  onOperation: (listener) => subscription("launcher:operation", listener),
  onLog: (listener) => subscription("launcher:log", listener),
  onUpdateState: (listener) => subscription("launcher:update-state", listener),
});
