import { createHash } from "node:crypto";
import { realpathSync } from "node:fs";
import { basename, dirname, join, posix, resolve, win32 } from "node:path";
import type { AppConfig } from "./config";
import { getConfigDir } from "./config";
import type { InstalledCodexInterruptHook } from "./codex-integration-shared";

export const MANAGED_INTERRUPT_HOOK_START =
  "# Managed by codex-chatgpt-web: release the exact Responses request when its Codex turn is interrupted.";
export const MANAGED_INTERRUPT_HOOK_END =
  "# End codex-chatgpt-web interrupt lifecycle hook.";

function canonicalJson(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalJson);
  if (!value || typeof value !== "object") return value;
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, item]) => [key, canonicalJson(item)]),
  );
}

/** Match codex_config::version_for_toml for the normalized Interrupt command hook. */
export function codexInterruptHookHash(command: string): string {
  const identity = canonicalJson({
    event_name: "interrupt",
    hooks: [{
      type: "command",
      command,
      timeout: 3,
      async: false,
    }],
  });
  return `sha256:${createHash("sha256").update(JSON.stringify(identity)).digest("hex")}`;
}

function posixShellArgument(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

function cmdShellArgument(value: string): string {
  if (value.includes('"') || /[\r\n]/.test(value)) {
    throw new Error("Codex interrupt hook command contains an invalid Windows path character");
  }
  // Codex executes command hooks through cmd.exe /C on Windows. Quoting every argument preserves
  // spaces and shell metacharacters in the installed runtime path.
  return `"${value}"`;
}

export function codexInterruptHookCommand(
  config: Pick<AppConfig, "runtimeCommand">,
  home = getConfigDir(),
  platform: NodeJS.Platform = process.platform,
): string {
  const absoluteHome = platform === "win32" ? win32.resolve(home) : posix.resolve(home);
  const args = [...config.runtimeCommand, "--home", absoluteHome, "hook", "interrupt"];
  return args.map(platform === "win32" ? cmdShellArgument : posixShellArgument).join(" ");
}

function lineEnding(text: string): "\n" | "\r\n" | "\r" {
  return text.includes("\r\n") ? "\r\n" : text.includes("\n") ? "\n" : text.includes("\r") ? "\r" : "\n";
}

function interruptGroupCount(text: string): number {
  return text.split(/\r\n|\n|\r/).filter(line => /^\s*\[\[hooks\.Interrupt\]\]\s*(?:#.*)?$/.test(line)).length;
}

function managedMarkerCount(text: string): number {
  return text.split(MANAGED_INTERRUPT_HOOK_START).length - 1;
}

function canonicalConfigPath(configPath: string): string {
  const absolute = resolve(configPath);
  try {
    return realpathSync.native(absolute);
  } catch {
    try {
      return join(realpathSync.native(dirname(absolute)), basename(absolute));
    } catch {
      return absolute;
    }
  }
}

export function installCodexInterruptHook(
  text: string,
  configPath: string,
  config: Pick<AppConfig, "runtimeCommand">,
  replaceExisting = false,
): { text: string; installed: InstalledCodexInterruptHook } {
  return installCodexInterruptHookCommand(text, configPath, codexInterruptHookCommand(config), replaceExisting);
}

function hookCore(command: string, stateKey: string, ending: string, withEnd = true): string {
  return [
    MANAGED_INTERRUPT_HOOK_START,
    "[[hooks.Interrupt]]",
    "",
    "[[hooks.Interrupt.hooks]]",
    'type = "command"',
    `command = ${JSON.stringify(command)}`,
    "timeout = 3",
    "",
    `[hooks.state.${JSON.stringify(stateKey)}]`,
    `trusted_hash = ${JSON.stringify(codexInterruptHookHash(command))}`,
    ...(withEnd ? [MANAGED_INTERRUPT_HOOK_END] : []),
  ].join(ending);
}

// Recognize only the exact block generated by this installer. Some TOML editors
// drop its trailing comment. Accept that one loss only after validating the
// complete command, trust hash, canonical config path, group index and boundary.
// No arbitrary user hook is deleted or granted trust by this migration.
function readExistingHook(text: string, configPath: string) {
  const fail = () => { throw new Error("Existing interrupt hook is not an intact, verifiable managed block; no configuration was changed. Restore it from backup or review it manually."); };
  if (managedMarkerCount(text) !== 1 || text.split(MANAGED_INTERRUPT_HOOK_END).length > 2) return fail();
  const start = text.indexOf(MANAGED_INTERRUPT_HOOK_START);
  if (start > 0 && !/[\r\n]/.test(text[start - 1]!)) return fail();
  const ending = lineEnding(text.slice(start));
  const lines = text.slice(start).split(/\r\n|\n|\r/);
  let command: string;
  let stateKey: string;
  try {
    command = JSON.parse(lines[5]!.replace(/^command = /, ""));
    stateKey = JSON.parse(lines[8]!.match(/^\[hooks\.state\.(.+)\]$/)![1]!);
  } catch { return fail(); }
  const groupIndex = interruptGroupCount(text.slice(0, start));
  if (typeof command !== "string" || !command || /[\r\n]/.test(command)
    || stateKey !== `${canonicalConfigPath(configPath)}:interrupt:${groupIndex}:0`) return fail();
  const withEnd = lines[10] === MANAGED_INTERRUPT_HOOK_END;
  if (!withEnd && text.includes(MANAGED_INTERRUPT_HOOK_END)) return fail();
  const fragment = hookCore(command, stateKey, ending, withEnd);
  if (text.slice(start, start + fragment.length) !== fragment) return fail();
  const suffix = text.slice(start + fragment.length);
  if (suffix && !suffix.startsWith(ending)) return fail();
  // Never consume/ignore extra command or trust fields, even when the hash matches.
  if (!withEnd && suffix.trimStart() && !suffix.trimStart().startsWith("[")) return fail();
  return { start, fragment, command, stateKey, groupIndex };
}

export function installCodexInterruptHookCommand(
  text: string,
  configPath: string,
  command: string,
  replaceExisting = false,
): { text: string; installed: InstalledCodexInterruptHook } {
  const ending = lineEnding(text);
  if (managedMarkerCount(text) !== 0 || text.includes(MANAGED_INTERRUPT_HOOK_END)) {
    if (!replaceExisting) throw new Error("Codex config already contains a codex-chatgpt-web interrupt hook marker");
    const previous = readExistingHook(text, configPath);
    const fragment = hookCore(command, previous.stateKey, ending);
    return {
      text: text.slice(0, previous.start) + fragment + text.slice(previous.start + previous.fragment.length),
      installed: { command, groupIndex: previous.groupIndex, stateKey: previous.stateKey,
        trustedHash: codexInterruptHookHash(command), fragment, previousFragment: previous.fragment },
    };
  }
  const groupIndex = interruptGroupCount(text);
  const stateKey = `${canonicalConfigPath(configPath)}:interrupt:${groupIndex}:0`;
  const trustedHash = codexInterruptHookHash(command);
  const core = hookCore(command, stateKey, ending);
  const leading = text.length === 0
    ? ""
    : text.endsWith(`${ending}${ending}`)
      ? ""
      : text.endsWith(ending)
        ? ending
        : `${ending}${ending}`;
  const trailing = text.length > 0 && text.endsWith(ending) ? ending : "";
  const fragment = `${leading}${core}${trailing}`;
  return {
    text: `${text}${fragment}`,
    installed: { command, groupIndex, stateKey, trustedHash, fragment },
  };
}

export function verifyCodexInterruptHook(text: string, installed: InstalledCodexInterruptHook): void {
  const first = text.indexOf(installed.fragment);
  if (first < 0 || text.indexOf(installed.fragment, first + installed.fragment.length) >= 0) {
    throw new Error("Codex interrupt lifecycle hook changed after setup; refusing to overwrite it");
  }
  if (interruptGroupCount(text.slice(0, first)) !== installed.groupIndex) {
    throw new Error("Codex interrupt lifecycle hook order changed after setup; refusing to overwrite it");
  }
  if (managedMarkerCount(text) !== 1 || !text.includes(MANAGED_INTERRUPT_HOOK_END)) {
    throw new Error("Codex interrupt lifecycle hook markers changed after setup; refusing to overwrite them");
  }
  if (codexInterruptHookHash(installed.command) !== installed.trustedHash) {
    throw new Error("Codex interrupt lifecycle hook journal hash is invalid");
  }
}

export function restoreCodexInterruptHook(text: string, installed: InstalledCodexInterruptHook): string {
  verifyCodexInterruptHook(text, installed);
  const restored = text.replace(installed.fragment, installed.previousFragment ?? "");
  verifyCodexInterruptHookRestored(restored, installed);
  return restored;
}

export function verifyCodexInterruptHookRestored(text: string, installed?: InstalledCodexInterruptHook): void {
  if (installed?.previousFragment) {
    const configPath = installed.stateKey.replace(/:interrupt:\d+:0$/, "");
    const previous = readExistingHook(text, configPath);
    if (previous.fragment !== installed.previousFragment || previous.groupIndex !== installed.groupIndex) {
      throw new Error("Previous interrupt hook changed while disconnected; refusing to overwrite it");
    }
    return;
  }
  if (managedMarkerCount(text) !== 0 || text.includes(MANAGED_INTERRUPT_HOOK_END)) {
    throw new Error("Codex interrupt lifecycle hook is present while the bridge is disconnected");
  }
}
