import { useRef, useState } from "react";
import type { CodexCopy, Language, LauncherApi } from "./types";
import "./codex-copies.css";
import { copyLoginWords } from "./CodexCopyLoginPane";

type Words = { title: string; intro: string; name: string; mode: string; native: string; web: string; create: string; refresh: string; empty: string; busy: string; open: string; inspect: string; folder: string; archive: string; restore: string; archived: string; boundary: string; created: string; running: string; attention: string; checked: string; error: string; missing: string; preview: string };
export const copiesCopy: Record<Language, Words> = {
  "zh-CN": { title: "独立 Codex 副本", intro: "复用已安装的 Codex 程序，独立保存配置、任务、登录文件和桌面数据。不修改你原来的 Codex。", name: "副本名称", mode: "用途", native: "原生 Codex · 独立登录", web: "Star Moon 网页模型", create: "创建独立副本", refresh: "刷新列表", empty: "还没有副本。生成时不会复制任何凭据。", busy: "正在处理…", open: "启动独立桌面", inspect: "检查副本", folder: "打开副本文件夹", archive: "收起入口（保留数据）", restore: "恢复入口", archived: "显示已收起的副本", boundary: "配置隔离不是操作系统沙箱，也不增加额度。网页模式仍共用 Star Moon 的网页账号；共享的 Codex 程序升级会影响所有副本。桌面支持取决于本机版本，CLI 入口始终保留。", created: "已生成", running: "已启动进程", attention: "需要检查", checked: "本地目录读取通过；真实登录、模型与工具连接尚未验收。", error: "操作未完成。原有副本和数据已保留。可检查路径/版本，或新建替代副本；不要直接删除配置。", missing: "未找到 Codex 程序，请先安装 Codex，再刷新。", preview: "模拟预览：不创建目录、不启动程序。" },
  "zh-Hant": { title: "獨立 Codex 副本", intro: "重用已安裝的 Codex 程式，獨立儲存設定、工作、登入檔與桌面資料。不修改原本的 Codex。", name: "副本名稱", mode: "用途", native: "原生 Codex · 獨立登入", web: "Star Moon 網頁模型", create: "建立獨立副本", refresh: "重新整理", empty: "尚無副本；建立時不會複製憑據。", busy: "處理中…", open: "開啟獨立桌面", inspect: "檢查副本", folder: "開啟副本資料夾", archive: "收起入口（保留資料）", restore: "恢復入口", archived: "顯示已收起的副本", boundary: "設定隔離不是作業系統沙箱，也不增加額度。網頁模式共用 Star Moon 網頁帳號；共用程式升級會影響所有副本。桌面支援依本機版本而定，保留 CLI 入口。", created: "已建立", running: "已啟動程序", attention: "需要檢查", checked: "本機目錄讀取通過；登入、模型與工具尚未驗收。", error: "操作未完成，原有資料已保留。請檢查路徑或版本，也可建立替代副本。", missing: "找不到 Codex，請先安裝再重新整理。", preview: "模擬預覽：不建立資料夾、不啟動程式。" },
  en: { title: "Independent Codex copies", intro: "Reuse your installed Codex binary with separate config, tasks, login files and desktop data. Your original Codex stays unchanged.", name: "Copy name", mode: "Purpose", native: "Native Codex · separate sign-in", web: "Star Moon Web models", create: "Create independent copy", refresh: "Refresh list", empty: "No copies yet. No credentials are copied.", busy: "Working…", open: "Open independent desktop", inspect: "Check copy", folder: "Open copy folder", archive: "Hide entry (keep data)", restore: "Restore entry", archived: "Show hidden copies", boundary: "Configuration isolation is not an OS sandbox or extra quota. Web mode shares Star Moon's web account. Binary upgrades affect every copy. Desktop support depends on the installed version; a CLI launcher is retained.", created: "Created", running: "Process started", attention: "Needs review", checked: "Local catalog loads. Live login, model and tool connections are not yet verified.", error: "The operation did not finish. Existing data is retained. Check the installed path/version or create a replacement copy; do not delete config files.", missing: "Codex was not found. Install it and refresh.", preview: "Simulated preview: no files or processes are created." },
  fr: { title: "Copies Codex indépendantes", intro: "Réutilise Codex avec configuration, tâches, fichiers de connexion et données bureau séparés, sans modifier l’original.", name: "Nom", mode: "Usage", native: "Codex natif · connexion séparée", web: "Modèles Web Star Moon", create: "Créer une copie", refresh: "Actualiser", empty: "Aucune copie. Aucun identifiant n’est copié.", busy: "En cours…", open: "Ouvrir le bureau indépendant", inspect: "Vérifier", folder: "Ouvrir le dossier", archive: "Masquer sans supprimer", restore: "Restaurer l’entrée", archived: "Afficher les copies masquées", boundary: "Ce n’est ni un bac à sable système ni un quota supplémentaire. Le mode Web partage le compte Star Moon. Une mise à jour du programme affecte toutes les copies. Le bureau dépend de la version ; le lanceur CLI reste disponible.", created: "Créée", running: "Processus démarré", attention: "À vérifier", checked: "Catalogue local chargé ; connexion, modèle et outils restent à vérifier.", error: "Opération incomplète. Données conservées. Vérifiez le chemin/version ou créez une autre copie.", missing: "Codex introuvable. Installez-le puis actualisez.", preview: "Simulation : aucun fichier ni processus créé." },
  ja: { title: "独立した Codex コピー", intro: "インストール済み Codex を再利用し、設定・タスク・認証ファイル・デスクトップデータを分離します。元の Codex は変更しません。", name: "コピー名", mode: "用途", native: "標準 Codex・個別ログイン", web: "Star Moon Web モデル", create: "独立コピーを作成", refresh: "一覧を更新", empty: "コピーはありません。認証情報は複製しません。", busy: "処理中…", open: "独立デスクトップを起動", inspect: "コピーを確認", folder: "フォルダーを開く", archive: "入口を非表示（データ保持）", restore: "入口を復元", archived: "非表示のコピーも表示", boundary: "設定分離は OS サンドボックスではなく、利用枠も増えません。Web は Star Moon のアカウントを共有します。プログラム更新は全コピーに影響します。デスクトップの対応はバージョン依存で、CLI 起動ファイルも残します。", created: "作成済み", running: "プロセス起動済み", attention: "要確認", checked: "ローカルカタログ読取成功。ログイン・モデル・ツールは未検証です。", error: "操作未完了。データは保持されます。パスやバージョンを確認するか新しいコピーを作成してください。", missing: "Codex が見つかりません。インストール後に更新してください。", preview: "表示専用。ファイル作成やプログラム起動は行いません。" },
  ru: { title: "Независимые копии Codex", intro: "Общий установленный Codex, отдельные настройки, задачи, файлы входа и данные рабочего стола. Исходный Codex не меняется.", name: "Название", mode: "Назначение", native: "Codex · отдельный вход", web: "Веб-модели Star Moon", create: "Создать копию", refresh: "Обновить список", empty: "Копий нет. Учётные данные не копируются.", busy: "Обработка…", open: "Открыть отдельное окно", inspect: "Проверить", folder: "Открыть папку", archive: "Скрыть, сохранив данные", restore: "Восстановить запись", archived: "Показать скрытые копии", boundary: "Это не системная песочница и не дополнительная квота. Веб-режим использует аккаунт Star Moon. Обновление программы влияет на все копии. Поддержка окна зависит от версии; CLI сохранён.", created: "Создано", running: "Процесс запущен", attention: "Нужна проверка", checked: "Локальный каталог загружен; вход, модель и инструменты ещё не проверены.", error: "Операция не завершена, данные сохранены. Проверьте путь/версию или создайте другую копию.", missing: "Codex не найден. Установите и обновите список.", preview: "Демонстрация без файлов и процессов." },
  de: { title: "Unabhängige Codex-Kopien", intro: "Nutzt das installierte Codex mit separaten Einstellungen, Aufgaben, Anmeldedateien und Desktop-Daten. Das Original bleibt unverändert.", name: "Name der Kopie", mode: "Verwendung", native: "Codex · separate Anmeldung", web: "Star Moon Web-Modelle", create: "Unabhängige Kopie erstellen", refresh: "Liste aktualisieren", empty: "Noch keine Kopien. Zugangsdaten werden nicht kopiert.", busy: "In Bearbeitung…", open: "Unabhängigen Desktop öffnen", inspect: "Kopie prüfen", folder: "Ordner öffnen", archive: "Eintrag ausblenden, Daten behalten", restore: "Eintrag wiederherstellen", archived: "Ausgeblendete Kopien anzeigen", boundary: "Konfigurationstrennung ist keine OS-Sandbox und kein zusätzliches Kontingent. Web teilt das Star-Moon-Konto. Programmupdates betreffen alle Kopien. Desktop-Unterstützung hängt von der Version ab; der CLI-Starter bleibt erhalten.", created: "Erstellt", running: "Prozess gestartet", attention: "Prüfung erforderlich", checked: "Lokaler Katalog geladen; Anmeldung, Modell und Tools noch nicht geprüft.", error: "Vorgang unvollständig. Daten bleiben erhalten. Pfad/Version prüfen oder eine Ersatzkopie erstellen.", missing: "Codex nicht gefunden. Installieren und aktualisieren.", preview: "Simulation ohne Dateien oder Prozesse." },
};

export function CodexCopiesPanel({ api, language, preview = false, disabled = false }: { api: LauncherApi; language: Language; preview?: boolean; disabled?: boolean }) {
  const words = copiesCopy[language];
  const [items, setItems] = useState<CodexCopy[]>([]), [name, setName] = useState("Star Moon Codex"), [mode, setMode] = useState<"native" | "web">("web");
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [loaded, setLoaded] = useState(false), [available, setAvailable] = useState(true), [showArchived, setShowArchived] = useState(false);
  const [loginChecks, setLoginChecks] = useState<Record<string, string>>({});
  const lock = useRef(false);
  const refresh = async () => { const result = await api.codexCopies(); setItems(result.copies); setAvailable(Boolean(result.runtime.codexExecutable)); setLoaded(true); };
  const run = async (action: () => Promise<unknown>) => {
    if (preview || disabled || lock.current) return;
    lock.current = true; setBusy(true); setError(null);
    try { await action(); await refresh(); }
    catch (error) { const code = String(error instanceof Error ? error.message : error).match(/SM_COPY_[A-Z_]+/)?.[0]; setError(code || "SM_COPY_OPERATION_FAILED"); }
    finally { lock.current = false; setBusy(false); }
  };
  const blocked = disabled || busy || preview;
  return <details className="codex-copies" onToggle={event => { if (event.currentTarget.open && !loaded) void run(refresh); }}>
    <summary>{words.title}</summary><p>{words.intro}</p><p className="codex-copy-boundary">{preview ? words.preview : words.boundary}</p>
    <div className="codex-copy-form"><label>{words.name}<input value={name} maxLength={60} disabled={blocked} onChange={event => setName(event.target.value)} /></label>
      <label>{words.mode}<select value={mode} disabled={blocked} onChange={event => setMode(event.target.value as "native" | "web")}><option value="web">{words.web}</option><option value="native">{words.native}</option></select></label>
      <button type="button" className="button-primary" disabled={blocked || !name.trim() || !available} onClick={() => void run(() => api.createCodexCopy({ name, mode }))}>{busy ? words.busy : words.create}</button>
      <button type="button" className="button-secondary" disabled={blocked} onClick={() => void run(refresh)}>{words.refresh}</button></div>
    {!available ? <p role="alert">{words.missing}</p> : null}
    {error ? <p role="alert">{words.error}<br /><code>{error}</code></p> : null}
    <label className="codex-copy-archive-toggle"><input type="checkbox" checked={showArchived} onChange={event => setShowArchived(event.target.checked)} />{words.archived}</label>
    {!items.length && loaded ? <p>{words.empty}</p> : null}
    <ul className="codex-copy-list">{items.filter(item => showArchived || !item.archived).map(item => <li key={item.id}>
      <header><strong>{item.name}</strong><span>{item.status === "running" ? words.running : item.status === "needs-attention" ? words.attention : words.created}</span></header>
      <p>{item.mode === "web" ? words.web : words.native} · {item.codexVersion}</p>
      <dl><dt>CODEX_HOME</dt><dd><code>{item.home}</code></dd><dt>Desktop</dt><dd><code>{item.desktopData}</code></dd><dt>CLI</dt><dd><code>{item.cliLauncher}</code></dd></dl>
      {item.verification ? <p className="codex-copy-boundary">{words.checked}</p> : null}
      {loginChecks[item.id] ? <p><code>Codex login: {loginChecks[item.id]}</code></p> : null}
      {item.issues?.length ? <p role="status"><code>{item.issues.join("; ")}</code></p> : null}
      <div className="codex-copy-actions"><button type="button" disabled={blocked || item.archived || !item.desktopAvailable || item.status === "needs-attention"} onClick={() => void run(() => api.openCodexCopy(item.id))}>{words.open}</button>
        <button type="button" disabled={blocked || item.archived || item.status === "needs-attention"} onClick={() => void run(() => api.startCodexCopyLogin(item.id))}>{copyLoginWords[language].open}</button>
        <button type="button" disabled={blocked} onClick={() => void run(async () => { const result = await api.inspectCodexCopy(item.id); setLoginChecks(previous => ({ ...previous, [item.id]: result.login || "not-verified" })); if (result.issues.length) setError("SM_COPY_REQUIRES_REVIEW"); })}>{words.inspect}</button>
        <button type="button" disabled={blocked} onClick={() => void run(() => api.openCodexCopyFolder(item.id))}>{words.folder}</button>
        <button type="button" disabled={blocked} onClick={() => void run(() => api.archiveCodexCopy(item.id, !item.archived))}>{item.archived ? words.restore : words.archive}</button></div>
    </li>)}</ul>
  </details>;
}
