import type { Language } from "./types";

const en = {
  chapter: "Your first journey", account: "Let’s meet your ChatGPT.", accountBody: "Sign in on the official page in this app’s private browser. Keep your password and verification code on that page; do not share them here.",
  returnFromLogin: "Return to the guide", prepare: "We’ll take it from here.", prepareBody: "With your permission, we will send one short test message, verify its full response, and configure the local Codex integration. The message uses your account’s allowance. Existing custom routes are backed up by the installer. A restart may be needed.",
  consent: "Agree and configure", automatic: "We’re configuring this step for you.", retry: "Try this step again", details: "What happens in this step?", resume: "Continue from the saved state",
  smoke: "A small message. A real response.", install: "Bringing the connection home.", catalog: "Let Codex meet the new connection.", catalogBody: "Fully quit and reopen Codex once. Keep this guide open. We’ll automatically continue when the native model catalog has actually been requested; a restart alone is not proof of success.",
  tunnel: "A path between cloud and home.", credentials: "Give this path its address.", connector: "One last connection in ChatGPT.", verify: "Let’s check the whole connection.",
  agentdock: "Bring the connection back home.", agentdockBody: "Finish the AgentDock setup below before moving on. Open ChatGPT here and approve access yourself. Continue requires a checked AgentDock connection, not authorization alone.",
  agentdockWaiting: "Set up and check AgentDock below", agentdockContinue: "AgentDock checked — continue", agentdockBrowser: "ChatGPT connector settings",
  goalWebModel: "Web model", goalLocalConnection: "Local connection", goalBeginJourney: "Begin the journey",
  "endless-night": "Endless Night", endlessNightBody: "One choice before your workspace. This experimental feature is optional; we keep your current setting and never enable it automatically.",
  endlessNightOff: "Continue with Endless Night off", endlessNightOn: "Continue with Endless Night on", endlessNightManualContinue: "Continue in manual mode",
  endlessNightManualSaved: "The switch shows your saved preference only. Endless Night is not active in manual mode, and this page does not change that preference.",
  endlessNightPreview: "Simulated preview only: this switch changes the page display, not your saved settings. It sends no request and uses no account allowance.", endlessNightPreviewToggle: "Simulate the Endless Night switch",
  endlessNightRestart: "Your preference is saved. Fully quit and reopen Codex, keeping this guide open. Continue becomes available only when the native model catalog has actually been requested again.",
  endlessNightRecheck: "Check the catalog status again", endlessNightUnavailable: "Endless Night requires a configured automatic-mode connection.",
  complete: "This connection is ready.", completeBody: "The selected local integration and runtime checks passed. This does not verify the future Work sandbox workflow.", manualCompleteBody: "The local manual-mode runtime is ready. You still select the connector, model and effort in ChatGPT yourself each turn; this mode cannot verify that selection.",
  enter: "Enter the workspace", connectorDone: "I’ve added it — continue", saved: "Use the credentials already saved on this device", scope: "This build connects through the existing OpenAI tunnel. Temporary-address, Cloudflare and VPS guides are still being integrated; they are not presented as working options yet.",
  interrupted: "This step did not finish. Nothing has been marked complete. Check the details and retry when you’re ready.", waiting: "Waiting for the required action", verified: "Verification passed", viewDetails: "View diagnostic details", editCredentials: "Enter different credentials",
};
type JourneyCopy = { [K in keyof typeof en]: string };
export const journeyCopy: Record<Language, JourneyCopy> = {
  en,
  "zh-CN": {
    chapter: "你的初次旅程", account: "先认识你的 ChatGPT。", accountBody: "在本应用的独立浏览器中，打开官方页面登录。密码与验证码只填在登录页面，不需要交给我们。",
    returnFromLogin: "返回引导", prepare: "接下来，交给我们。", prepareBody: "经你同意，我们会发送一条简短测试消息，确认完整回复，再配置本地 Codex 接入。测试会使用账号额度；安装器会备份已有自定义路由。配置后可能需要重启 Codex。",
    consent: "同意并开始配置", automatic: "这一步由我们自动完成。", retry: "重试这一步", details: "这一步会做什么？", resume: "从已保存的进度继续",
    smoke: "一句问候，确认连接。", install: "把连接，带到你的电脑。", catalog: "让 Codex 认识新连接。", catalogBody: "请完整退出 Codex，再重新打开一次。保持本引导开启；检测到原生模型目录确实被请求后，我们会自动进入下一页。重启本身不等于验证成功。",
    tunnel: "为云端与本地，牵一条线。", credentials: "让这条路，有一个地址。", connector: "在 ChatGPT 中，接好最后一端。", verify: "最后，让我们一起确认。",
    agentdock: "让连接，回到你身边。", agentdockBody: "继续前，先完成下方的 AgentDock 配置。在这里打开 ChatGPT，由你本人确认授权。还需要检查 AgentDock 连接，不能只凭授权成功就进入下一步。",
    agentdockWaiting: "请在下方配置并检查 AgentDock", agentdockContinue: "AgentDock 已检查，继续", agentdockBrowser: "ChatGPT 连接器设置",
    goalWebModel: "网页模型", goalLocalConnection: "本地连接", goalBeginJourney: "开启旅程",
    "endless-night": "永夜", endlessNightBody: "进入工作台前，留一个选择给你。永夜是可选的实验性功能；我们保留当前设置，不会自动开启。",
    endlessNightOff: "保持永夜关闭，继续", endlessNightOn: "保持永夜开启，继续", endlessNightManualContinue: "继续使用手动模式",
    endlessNightManualSaved: "开关仅展示已保存的偏好。永夜在手动模式下不生效，此页也不会更改这项偏好。",
    endlessNightPreview: "仅作模拟预览：开关只改变页面展示，不保存设置、不发送请求，也不消耗账号额度。", endlessNightPreviewToggle: "模拟永夜开关",
    endlessNightRestart: "偏好已保存。请完整退出并重新打开 Codex，保持本引导开启。只有再次收到原生模型目录的真实请求后，才可以继续。",
    endlessNightRecheck: "重新检查目录状态", endlessNightUnavailable: "永夜需要已完成配置的自动化模式连接。",
    complete: "这一段连接，已经就绪。", completeBody: "本次选择的本地接入和运行时检查已经通过。这不代表未来的 Work 沙箱工作流已经验收。", manualCompleteBody: "手动模式的本地运行环境已就绪。每次对话仍需你在 ChatGPT 中选择连接器、模型和思考等级；此模式不会检查或验证你的网页选择。",
    enter: "进入工作台", connectorDone: "我已添加，继续", saved: "使用这台设备上已保存的凭据", scope: "当前开发版接通的是原有 OpenAI Tunnel。临时地址、Cloudflare 与 VPS 的引导仍在接入，不会把尚未实现的选项展示成可用功能。",
    interrupted: "这一步尚未完成，没有被标记为成功。请查看详情，准备好后再重试。", waiting: "等待必要操作", verified: "检查已通过", viewDetails: "查看诊断详情", editCredentials: "填写其他凭据",
  },
  "zh-Hant": {
    chapter: "你的初次旅程", account: "先認識你的 ChatGPT。", accountBody: "在本應用程式的獨立瀏覽器中，開啟官方頁面登入。密碼與驗證碼只填在登入頁面，不需要交給我們。",
    returnFromLogin: "返回引導", prepare: "接下來，交給我們。", prepareBody: "經你同意，我們會傳送一條簡短測試訊息，確認完整回覆，再設定本機 Codex 接入。測試會使用帳號額度；安裝程式會備份已有自訂路由。設定後可能需要重新啟動 Codex。",
    consent: "同意並開始設定", automatic: "這一步由我們自動完成。", retry: "重試這一步", details: "這一步會做什麼？", resume: "從已儲存的進度繼續",
    smoke: "一句問候，確認連線。", install: "把連線，帶到你的電腦。", catalog: "讓 Codex 認識新連線。", catalogBody: "請完全結束 Codex，再重新開啟一次。保持本引導開啟；檢查到原生模型目錄確實被請求後，我們會自動進入下一頁。重新啟動本身不等於驗證成功。",
    tunnel: "為雲端與本機，牽一條線。", credentials: "讓這條路，有一個地址。", connector: "在 ChatGPT 中，接好最後一端。", verify: "最後，讓我們一起確認。",
    agentdock: "讓連線，回到你身邊。", agentdockBody: "繼續前，先完成下方的 AgentDock 設定。在這裡開啟 ChatGPT，由你本人確認授權。還需要檢查 AgentDock 連線，不能只憑授權成功就進入下一步。",
    agentdockWaiting: "請在下方設定並檢查 AgentDock", agentdockContinue: "AgentDock 已檢查，繼續", agentdockBrowser: "ChatGPT 連接器設定",
    goalWebModel: "網頁模型", goalLocalConnection: "本機連線", goalBeginJourney: "開啟旅程",
    "endless-night": "永夜", endlessNightBody: "進入工作台前，留一個選擇給你。永夜是可選的實驗性功能；我們保留目前設定，不會自動開啟。",
    endlessNightOff: "保持永夜關閉，繼續", endlessNightOn: "保持永夜開啟，繼續", endlessNightManualContinue: "繼續使用手動模式",
    endlessNightManualSaved: "開關僅展示已儲存的偏好。永夜在手動模式下不生效，此頁也不會更改這項偏好。",
    endlessNightPreview: "僅作模擬預覽：開關只改變頁面展示，不儲存設定、不傳送請求，也不消耗帳號額度。", endlessNightPreviewToggle: "模擬永夜開關",
    endlessNightRestart: "偏好已儲存。請完全結束並重新開啟 Codex，保持本引導開啟。只有再次收到原生模型目錄的真實請求後，才可以繼續。",
    endlessNightRecheck: "重新檢查目錄狀態", endlessNightUnavailable: "永夜需要已完成設定的自動化模式連線。",
    complete: "這一段連線，已經就緒。", completeBody: "本次選擇的本機接入和執行環境檢查已經通過。這不代表未來的 Work 沙箱工作流程已經驗收。", manualCompleteBody: "手動模式的本機執行環境已就緒。每次對話仍需你在 ChatGPT 中選擇連接器、模型和思考等級；此模式不會檢查或驗證你的網頁選擇。",
    enter: "進入工作台", connectorDone: "我已新增，繼續", saved: "使用這台裝置上已儲存的憑證", scope: "目前開發版接通的是原有 OpenAI Tunnel。臨時地址、Cloudflare 與 VPS 的引導仍在接入，不會把尚未實現的選項展示成可用功能。",
    interrupted: "這一步尚未完成，沒有被標記為成功。請查看詳情，準備好後再重試。", waiting: "等待必要操作", verified: "檢查已通過", viewDetails: "查看診斷詳情", editCredentials: "填寫其他憑證",
  },
  fr: {
    chapter: "Votre premier voyage", account: "Retrouvons votre ChatGPT.", accountBody: "Connectez-vous sur la page officielle dans le navigateur privé de cette application. Saisissez votre mot de passe et votre code uniquement sur cette page.",
    returnFromLogin: "Revenir au guide", prepare: "Nous prenons le relais.", prepareBody: "Avec votre accord, nous enverrons un court message de test, vérifierons sa réponse complète et configurerons Codex local. Le test utilise votre quota. L’installateur sauvegarde les routes personnalisées existantes. Un redémarrage peut être nécessaire.",
    consent: "Accepter et configurer", automatic: "Nous réalisons cette étape pour vous.", retry: "Réessayer cette étape", details: "Que fait cette étape ?", resume: "Reprendre la progression enregistrée",
    smoke: "Un petit message, une vraie réponse.", install: "La connexion arrive chez vous.", catalog: "Présentons la connexion à Codex.", catalogBody: "Quittez complètement Codex puis rouvrez-le. Gardez ce guide ouvert : nous continuerons quand le catalogue de modèles aura réellement été demandé. Le redémarrage seul ne prouve pas la réussite.",
    tunnel: "Un chemin du cloud à votre ordinateur.", credentials: "Donnons une adresse à ce chemin.", connector: "Le dernier lien dans ChatGPT.", verify: "Vérifions la connexion ensemble.",
    agentdock: "Ramenons la connexion chez vous.", agentdockBody: "Terminez la configuration AgentDock ci-dessous. Ouvrez ChatGPT ici et confirmez vous-même l’accès. Pour continuer, la connexion AgentDock doit être vérifiée : l’autorisation seule ne suffit pas.",
    agentdockWaiting: "Configurez et vérifiez AgentDock ci-dessous", agentdockContinue: "AgentDock vérifié — continuer", agentdockBrowser: "Paramètres des connecteurs ChatGPT",
    goalWebModel: "Modèle Web", goalLocalConnection: "Connexion locale", goalBeginJourney: "Commencer le voyage",
    "endless-night": "Nuit sans fin", endlessNightBody: "Un choix avant votre espace de travail. Cette fonction expérimentale est facultative : nous conservons votre réglage actuel et ne l’activons jamais automatiquement.",
    endlessNightOff: "Continuer avec Nuit sans fin désactivée", endlessNightOn: "Continuer avec Nuit sans fin activée", endlessNightManualContinue: "Continuer en mode manuel",
    endlessNightManualSaved: "L’interrupteur indique uniquement votre préférence enregistrée. Nuit sans fin n’est pas active en mode manuel, et cette page ne modifie pas cette préférence.",
    endlessNightPreview: "Aperçu simulé uniquement : l’interrupteur change l’affichage, pas vos réglages enregistrés. Aucune requête n’est envoyée et aucun quota n’est utilisé.", endlessNightPreviewToggle: "Simuler l’interrupteur Nuit sans fin",
    endlessNightRestart: "Votre préférence est enregistrée. Quittez complètement Codex puis rouvrez-le en gardant ce guide ouvert. Vous pourrez continuer lorsque le catalogue natif de modèles aura réellement été demandé à nouveau.",
    endlessNightRecheck: "Revérifier l’état du catalogue", endlessNightUnavailable: "Nuit sans fin nécessite une connexion configurée en mode automatique.",
    complete: "Cette connexion est prête.", completeBody: "Les contrôles de l’intégration locale choisie ont réussi. Cela ne valide pas le futur flux de travail Work.", manualCompleteBody: "L’environnement local manuel est prêt. À chaque tour, choisissez vous-même le connecteur, le modèle et l’effort dans ChatGPT ; ce mode ne vérifie pas ce choix.",
    enter: "Ouvrir l’espace de travail", connectorDone: "Je l’ai ajouté — continuer", saved: "Utiliser les identifiants enregistrés sur cet appareil", scope: "Cette version utilise le tunnel OpenAI existant. Les guides d’adresse temporaire, Cloudflare et VPS restent en développement et ne sont pas proposés comme fonctionnels.",
    interrupted: "Cette étape n’a pas abouti. Rien n’a été marqué comme terminé. Consultez les détails puis réessayez.", waiting: "En attente de votre intervention", verified: "Vérification réussie", viewDetails: "Voir les détails du diagnostic", editCredentials: "Saisir d’autres identifiants",
  },
  ja: {
    chapter: "はじめての旅", account: "あなたの ChatGPT とつながろう。", accountBody: "このアプリ専用のブラウザーで公式ページにログインしてください。パスワードと認証コードはログインページだけに入力し、ここで共有しないでください。",
    returnFromLogin: "ガイドに戻る", prepare: "ここからは、私たちにお任せを。", prepareBody: "同意後、短いテストメッセージを送り、完全な応答を確認してローカル Codex を設定します。テストにはアカウントの利用枠を使います。既存のカスタムルートはインストーラーが保存します。再起動が必要になる場合があります。",
    consent: "同意して設定する", automatic: "この手順は自動で進めます。", retry: "この手順を再試行", details: "この手順で行うこと", resume: "保存した状態から再開",
    smoke: "小さな挨拶で、応答を確認。", install: "つながりを、あなたの手元へ。", catalog: "新しい接続を Codex に知らせよう。", catalogBody: "Codex を完全に終了し、再び開いてください。ガイドは開いたままにしてください。モデル一覧が実際に取得されると自動で進みます。再起動だけでは成功と判定しません。",
    tunnel: "クラウドと手元を結ぶ道。", credentials: "この道に、アドレスを。", connector: "ChatGPT 側の最後の接続。", verify: "最後に、一緒に確認しよう。",
    agentdock: "つながりを、あなたの手元へ。", agentdockBody: "次へ進む前に、下で AgentDock を設定してください。この画面で ChatGPT を開き、本人がアクセスを許可します。認証だけでなく、AgentDock の接続確認も必要です。",
    agentdockWaiting: "下で AgentDock を設定・確認してください", agentdockContinue: "AgentDock 確認済み — 次へ", agentdockBrowser: "ChatGPT のコネクタ設定",
    goalWebModel: "Web モデル", goalLocalConnection: "ローカル接続", goalBeginJourney: "旅をはじめる",
    "endless-night": "永夜", endlessNightBody: "ワークスペースに入る前に、ひとつ選択を。この試験的な機能は任意です。現在の設定を保ち、自動で有効にすることはありません。",
    endlessNightOff: "永夜を無効のまま続ける", endlessNightOn: "永夜を有効にして続ける", endlessNightManualContinue: "手動モードで続ける",
    endlessNightManualSaved: "スイッチは保存済みの設定のみを表示します。永夜は手動モードでは動作せず、このページで設定が変更されることもありません。",
    endlessNightPreview: "表示のみのシミュレーションです。スイッチは画面だけを変更し、設定を保存せず、リクエストの送信やアカウントの利用枠の消費もしません。", endlessNightPreviewToggle: "永夜スイッチをシミュレーション",
    endlessNightRestart: "設定を保存しました。ガイドを開いたまま Codex を完全に終了し、再び開いてください。ネイティブのモデル一覧が実際に再取得されてから、次へ進めます。",
    endlessNightRecheck: "モデル一覧の状態を再確認", endlessNightUnavailable: "永夜には、設定済みの自動モードの接続が必要です。",
    complete: "この接続の準備ができました。", completeBody: "選択したローカル接続と実行環境の確認に成功しました。将来の Work サンドボックスの検証を意味するものではありません。", manualCompleteBody: "手動モードのローカル環境が整いました。毎回 ChatGPT でコネクタ、モデル、思考レベルを選んでください。このモードは Web 上の選択を確認しません。",
    enter: "ワークスペースへ", connectorDone: "追加しました — 次へ", saved: "この端末に保存した認証情報を使う", scope: "現在は既存の OpenAI Tunnel に接続します。一時アドレス、Cloudflare、VPS のガイドは開発中であり、利用可能な機能として表示しません。",
    interrupted: "この手順は完了していません。成功とは記録されていません。詳細を確認して再試行してください。", waiting: "必要な操作を待っています", verified: "確認に成功しました", viewDetails: "診断の詳細を見る", editCredentials: "別の認証情報を入力",
  },
  ru: {
    chapter: "Ваше первое путешествие", account: "Познакомимся с вашим ChatGPT.", accountBody: "Войдите на официальной странице в отдельном браузере приложения. Пароль и код подтверждения вводите только на странице входа; не передавайте их нам.",
    returnFromLogin: "Вернуться к руководству", prepare: "Дальше мы поможем сами.", prepareBody: "С вашего согласия мы отправим короткое тестовое сообщение, проверим полный ответ и настроим локальный Codex. Тест использует лимит аккаунта. Установщик сохраняет существующие пользовательские маршруты. Может потребоваться перезапуск.",
    consent: "Согласиться и настроить", automatic: "Этот шаг выполняется автоматически.", retry: "Повторить этот шаг", details: "Что происходит на этом шаге?", resume: "Продолжить с сохранённого состояния",
    smoke: "Короткое приветствие, настоящий ответ.", install: "Связь приходит на ваш компьютер.", catalog: "Познакомим Codex с новым подключением.", catalogBody: "Полностью закройте Codex и откройте его снова. Не закрывайте руководство. Мы продолжим после реального запроса каталога моделей. Сам перезапуск ещё не доказывает успех.",
    tunnel: "Путь между облаком и вашим домом.", credentials: "Дадим этому пути адрес.", connector: "Последнее подключение в ChatGPT.", verify: "Проверим подключение вместе.",
    agentdock: "Вернём связь на ваш компьютер.", agentdockBody: "Сначала завершите настройку AgentDock ниже. Откройте ChatGPT здесь и лично разрешите доступ. Чтобы продолжить, нужно проверить подключение AgentDock: одной авторизации недостаточно.",
    agentdockWaiting: "Настройте и проверьте AgentDock ниже", agentdockContinue: "AgentDock проверен — продолжить", agentdockBrowser: "Настройки коннекторов ChatGPT",
    goalWebModel: "Веб-модель", goalLocalConnection: "Локальная связь", goalBeginJourney: "Начать путь",
    "endless-night": "Бесконечная ночь", endlessNightBody: "Ещё один выбор перед рабочим пространством. Эта экспериментальная функция необязательна: мы сохраняем текущую настройку и никогда не включаем её автоматически.",
    endlessNightOff: "Продолжить с выключенной функцией", endlessNightOn: "Продолжить с включённой функцией", endlessNightManualContinue: "Продолжить в ручном режиме",
    endlessNightManualSaved: "Переключатель показывает только сохранённую настройку. В ручном режиме «Бесконечная ночь» не работает, и эта страница не меняет настройку.",
    endlessNightPreview: "Только имитация: переключатель меняет вид страницы, а не сохранённые настройки. Запросы не отправляются, лимит аккаунта не расходуется.", endlessNightPreviewToggle: "Имитировать переключатель «Бесконечная ночь»",
    endlessNightRestart: "Настройка сохранена. Полностью закройте Codex и откройте его снова, оставив руководство открытым. Продолжить можно будет только после реального повторного запроса встроенного каталога моделей.",
    endlessNightRecheck: "Проверить состояние каталога снова", endlessNightUnavailable: "Для «Бесконечной ночи» нужно настроенное подключение в автоматическом режиме.",
    complete: "Это подключение готово.", completeBody: "Проверки выбранной локальной интеграции и среды прошли успешно. Это не проверка будущего рабочего процесса Work.", manualCompleteBody: "Локальная среда ручного режима готова. В каждом ходе сами выбирайте коннектор, модель и уровень размышления в ChatGPT; этот режим не проверяет ваш выбор.",
    enter: "Войти в рабочее пространство", connectorDone: "Я добавил — продолжить", saved: "Использовать данные, сохранённые на этом устройстве", scope: "Эта версия использует существующий OpenAI Tunnel. Руководства по временному адресу, Cloudflare и VPS ещё разрабатываются и пока не предлагаются как готовые функции.",
    interrupted: "Этот шаг не завершён и не отмечен как успешный. Проверьте подробности и повторите, когда будете готовы.", waiting: "Ожидается необходимое действие", verified: "Проверка пройдена", viewDetails: "Посмотреть диагностику", editCredentials: "Ввести другие данные",
  },
  de: {
    chapter: "Deine erste Reise", account: "Lernen wir dein ChatGPT kennen.", accountBody: "Melde dich auf der offiziellen Seite im eigenen Browser dieser App an. Passwort und Bestätigungscode gehören nur auf die Anmeldeseite, nicht in diesen Chat.",
    returnFromLogin: "Zurück zur Anleitung", prepare: "Ab hier übernehmen wir.", prepareBody: "Mit deiner Zustimmung senden wir eine kurze Testnachricht, prüfen die vollständige Antwort und richten die lokale Codex-Anbindung ein. Der Test verbraucht Kontokontingent. Der Installer sichert bestehende eigene Routen. Ein Neustart kann nötig sein.",
    consent: "Zustimmen und einrichten", automatic: "Diesen Schritt erledigen wir automatisch.", retry: "Diesen Schritt wiederholen", details: "Was passiert in diesem Schritt?", resume: "Mit dem gespeicherten Stand fortfahren",
    smoke: "Ein kleiner Gruß, eine echte Antwort.", install: "Die Verbindung kommt zu dir.", catalog: "Stellen wir Codex die Verbindung vor.", catalogBody: "Beende Codex vollständig und öffne es erneut. Lass diese Anleitung offen. Sobald der Modellkatalog tatsächlich angefordert wurde, geht es automatisch weiter. Der Neustart allein ist noch kein Erfolgsnachweis.",
    tunnel: "Ein Weg zwischen Cloud und Zuhause.", credentials: "Geben wir diesem Weg eine Adresse.", connector: "Die letzte Verbindung in ChatGPT.", verify: "Prüfen wir die Verbindung gemeinsam.",
    agentdock: "Die Verbindung kommt zurück zu dir.", agentdockBody: "Richte zuerst AgentDock unten ein. Öffne ChatGPT hier und gib den Zugriff selbst frei. Zum Fortfahren muss die AgentDock-Verbindung geprüft sein; die Freigabe allein reicht nicht.",
    agentdockWaiting: "AgentDock unten einrichten und prüfen", agentdockContinue: "AgentDock geprüft — weiter", agentdockBrowser: "ChatGPT-Connector-Einstellungen",
    goalWebModel: "Web-Modell", goalLocalConnection: "Lokale Verbindung", goalBeginJourney: "Reise beginnen",
    "endless-night": "Endlose Nacht", endlessNightBody: "Eine Entscheidung vor deinem Arbeitsbereich. Diese experimentelle Funktion ist freiwillig: Wir behalten deine aktuelle Einstellung bei und aktivieren sie nie automatisch.",
    endlessNightOff: "Mit ausgeschalteter Endloser Nacht weiter", endlessNightOn: "Mit eingeschalteter Endloser Nacht weiter", endlessNightManualContinue: "Im manuellen Modus fortfahren",
    endlessNightManualSaved: "Der Schalter zeigt nur deine gespeicherte Einstellung. Endlose Nacht ist im manuellen Modus nicht aktiv, und diese Seite ändert die Einstellung nicht.",
    endlessNightPreview: "Nur eine simulierte Vorschau: Der Schalter ändert die Anzeige, nicht deine gespeicherten Einstellungen. Es werden keine Anfragen gesendet und kein Kontokontingent verbraucht.", endlessNightPreviewToggle: "Den Schalter für Endlose Nacht simulieren",
    endlessNightRestart: "Deine Einstellung ist gespeichert. Beende Codex vollständig und öffne es erneut; lass die Anleitung offen. Erst wenn der native Modellkatalog tatsächlich erneut angefordert wurde, kannst du fortfahren.",
    endlessNightRecheck: "Katalogstatus erneut prüfen", endlessNightUnavailable: "Endlose Nacht benötigt eine eingerichtete Verbindung im automatischen Modus.",
    complete: "Diese Verbindung ist bereit.", completeBody: "Die Prüfungen der gewählten lokalen Integration und Laufzeit waren erfolgreich. Das bestätigt nicht den zukünftigen Work-Sandbox-Ablauf.", manualCompleteBody: "Die lokale Umgebung im manuellen Modus ist bereit. Wähle in ChatGPT bei jedem Durchlauf selbst Connector, Modell und Denkaufwand. Dieser Modus prüft deine Auswahl nicht.",
    enter: "Zum Arbeitsbereich", connectorDone: "Hinzugefügt — weiter", saved: "Die auf diesem Gerät gespeicherten Zugangsdaten nutzen", scope: "Diese Version nutzt den bestehenden OpenAI Tunnel. Anleitungen für temporäre Adressen, Cloudflare und VPS werden noch integriert und nicht als fertige Funktionen angeboten.",
    interrupted: "Dieser Schritt ist nicht abgeschlossen und wurde nicht als erfolgreich markiert. Prüfe die Details und versuche es erneut.", waiting: "Warten auf den nötigen Schritt", verified: "Prüfung bestanden", viewDetails: "Diagnosedetails ansehen", editCredentials: "Andere Zugangsdaten eingeben",
  },
};
