import type { Language } from "./types";

const en = {
  book: "Book of the Moon", connection: "Connection", chapters: "Book chapters", leaf: "A page between cloud and home",
  title: "Let the moonlight reach you.", intro: "Pluck the lunar string. A signal leaves this page, and we wait for an answer.",
  check: "Test connection", sending: "The lunar string carries your signal…", idle: "The moon is waiting.",
  success: "The moon goddess answered your prayer", successDetail: "Connection handshake succeeded",
  failure: "The moon goddess did not answer your prayer", timeoutDetail: "Your connection handshake timed out",
  errorDetail: "The connection check failed", localReady: "Local checks passed; the remote handshake is still unverified.",
  dimmed: "The moonlight has grown faint, but it has not disappeared.", orange: "An orange cloud.",
  repair: "Turn to the repair page", retry: "Try again", configure: "Connection settings", details: "Diagnostic details",
  demo: "UI PREVIEW · These results are demonstrations, not live connections.", demoSuccess: "Demo: successful handshake", demoTimeout: "Demo: orange-cloud timeout",
  scope: "Checks your saved AgentDock MCP connection. A handshake here is not proof that the web conversation can call its tools; complete that verification in the embedded browser.",
  routes: "Give the moonlight an address", routeIntro: "Cloudflare is our ‘orange cloud’ joke: orange, and shaped like a cloud. The joke is not a diagnosis or an endorsement.",
  fixed: "Your domain + Cloudflare Tunnel", fixedBody: "A stable-address option. Reuse a domain you own or register one where you prefer. The tunnel points it to your local MCP service; a domain alone is not a server.",
  temporary: "Temporary address", temporaryBody: "Useful for a trial, with compatibility checks. Cloudflare Quick Tunnels do not support SSE and have no production SLA; do not assume every MCP transport will work.",
  vps: "VPS + HTTPS", vpsBody: "Another option if you maintain a server. Run or proxy the MCP service there and configure TLS, authentication and access limits. More maintenance is required.",
  routeStatus: "Guidance only · Installation branches are not connected yet", routeDocs: "Cloudflare documentation",
  tunnelRepair: "Check the hostname, DNS, tunnel process and target service. A timeout alone does not prove that Cloudflare is at fault.",
  authRepair: "Check your sign-in and connector authorization. Do not paste passwords or tokens into diagnostics.",
  localRepair: "Check whether the local service is running and whether the configured port and permissions are correct.",
  unknownRepair: "Check the actual error below before changing an address, replacing credentials or retrying a task.",
};
type BookCopy = { [K in keyof typeof en]: string };
export const moonBookCopy: Record<Language, BookCopy> = {
  en,
  "zh-CN": {
    book: "月之书", connection: "连接", chapters: "书中章节", leaf: "翻开云端与本地之间的一页",
    title: "让月光，抵达此处。", intro: "轻拨月弦，让一个信号离开书页。然后，等待月亮的回应。",
    check: "测试连接", sending: "月弦正向月亮传递信号……", idle: "月亮，正在等待。",
    success: "月神回应了你的祈祷", successDetail: "连接已成功握手",
    failure: "月神没有回应你的祈祷", timeoutDetail: "您的连接握手已超时",
    errorDetail: "连接检测失败", localReady: "本地检查已通过，远端握手尚未验证。",
    dimmed: "月光变得暗淡，但是并没有消失", orange: "一朵橘子云。",
    repair: "翻开修复页", retry: "再次尝试", configure: "连接设置", details: "诊断详情",
    demo: "仅预览 · 下方结果是动效演示，不代表真实连接。", demoSuccess: "演示：握手成功", demoTimeout: "演示：橘子云超时",
    scope: "检查你保存的 AgentDock MCP 连接。这里握手成功，不等于网页对话已能调用它的工具；请在内置浏览器里完成另一端的验证。",
    routes: "给月光，一个地址。", routeIntro: "为什么叫橘子云？因为 Cloudflare 是橘色的，又长得像一朵云。这是个梗，不是故障诊断，也不是商业背书。",
    fixed: "自有域名 + Cloudflare Tunnel", fixedBody: "想要稳定地址，可以复用已有域名，也可自行选择注册商购买。隧道将地址指向本地 MCP 服务；买域名不等于买好了服务器。",
    temporary: "临时地址", temporaryBody: "适合试用，但要验证传输兼容性。Cloudflare Quick Tunnel 不支持 SSE，也没有生产可用性承诺，不能保证每一种 MCP 连接都能使用。",
    vps: "VPS + HTTPS", vpsBody: "如果你愿意维护服务器，也可以在 VPS 部署或代理 MCP，再配置证书、认证和访问范围。需要承担更多维护工作。",
    routeStatus: "方案说明 · 安装分支仍待接入", routeDocs: "查看 Cloudflare 官方说明",
    tunnelRepair: "检查域名、DNS、隧道进程与目标服务。单凭超时不能认定是 Cloudflare 的问题，也不意味着必须再买一个域名。",
    authRepair: "检查登录状态和连接器授权。不要把密码或令牌粘贴进诊断信息。",
    localRepair: "检查本地服务是否启动，端口和访问权限是否正确。",
    unknownRepair: "先查看下面的实际错误，再决定是否更换地址、凭据或重试任务。",
  },
  "zh-Hant": {
    book: "月之書", connection: "連線", chapters: "書中章節", leaf: "翻開雲端與本機之間的一頁",
    title: "讓月光，抵達此處。", intro: "輕撥月弦，讓一個信號離開書頁。然後，等待月亮的回應。",
    check: "測試連線", sending: "月弦正向月亮傳遞信號……", idle: "月亮，正在等待。",
    success: "月神回應了你的祈禱", successDetail: "連線已成功握手",
    failure: "月神沒有回應你的祈禱", timeoutDetail: "您的連線握手已超時",
    errorDetail: "連線檢查失敗", localReady: "本機檢查已通過，遠端握手尚未驗證。",
    dimmed: "月光變得暗淡，但是並沒有消失", orange: "一朵橘子雲。",
    repair: "翻開修復頁", retry: "再次嘗試", configure: "連線設定", details: "診斷詳情",
    demo: "僅預覽 · 下方結果是動效演示，不代表真實連線。", demoSuccess: "演示：握手成功", demoTimeout: "演示：橘子雲超時",
    scope: "檢查你儲存的 AgentDock MCP 連線。這裡握手成功，不等於網頁對話已能呼叫它的工具；請在內建瀏覽器裡完成另一端的驗證。",
    routes: "給月光，一個地址。", routeIntro: "為什麼叫橘子雲？因為 Cloudflare 是橘色的，又長得像一朵雲。這是個梗，不是故障診斷，也不是商業背書。",
    fixed: "自有域名 + Cloudflare Tunnel", fixedBody: "想要穩定地址，可以沿用已有域名，也可自行選擇註冊商購買。隧道將地址指向本機 MCP 服務；買域名不等於買好了伺服器。",
    temporary: "臨時地址", temporaryBody: "適合試用，但要驗證傳輸相容性。Cloudflare Quick Tunnel 不支持 SSE，也沒有生產可用性承諾，不能保證每一種 MCP 連線都能使用。",
    vps: "VPS + HTTPS", vpsBody: "如果你願意維護伺服器，也可以在 VPS 部署或代理 MCP，再設定證書、認證和存取範圍。需要承擔更多維護工作。",
    routeStatus: "方案說明 · 安裝分支仍待接入", routeDocs: "查看 Cloudflare 官方說明",
    tunnelRepair: "檢查域名、DNS、隧道行程與目標服務。單憑超時不能認定是 Cloudflare 的問題，也不意味著必須再買一個域名。",
    authRepair: "檢查登入狀態和連接器授權。不要把密碼或令牌貼上進診斷資訊。",
    localRepair: "檢查本機服務是否啟動，連接埠和存取權限是否正確。",
    unknownRepair: "先查看下面的實際錯誤，再決定是否更換地址、憑證或重試任務。",
  },
  fr: {
    book: "Livre de la Lune", connection: "Connexion", chapters: "Chapitres du livre", leaf: "Une page entre le cloud et chez vous",
    title: "Que la lumière lunaire vous atteigne.", intro: "Pincez la corde lunaire. Un signal quitte la page, puis nous attendons une réponse.", check: "Tester la connexion", sending: "La corde lunaire transmet votre signal…", idle: "La lune attend.",
    success: "La déesse lunaire a répondu à votre prière", successDetail: "La négociation de connexion a réussi", failure: "La déesse lunaire n’a pas répondu à votre prière", timeoutDetail: "Le délai de négociation est dépassé", errorDetail: "La vérification a échoué", localReady: "Contrôles locaux réussis ; connexion distante non vérifiée.",
    dimmed: "La lumière de la lune faiblit, mais elle n’a pas disparu.", orange: "Un nuage orange.", repair: "Ouvrir la page de réparation", retry: "Réessayer", configure: "Réglages de connexion", details: "Diagnostic",
    demo: "APERÇU · Résultats simulés, sans connexion réelle.", demoSuccess: "Démo : connexion réussie", demoTimeout: "Démo : délai du nuage orange",
    scope: "Vérifie votre connexion MCP AgentDock enregistrée. Cela ne prouve pas que la conversation Web peut appeler ses outils ; vérifiez cet autre côté dans le navigateur intégré.",
    routes: "Une adresse pour le clair de lune", routeIntro: "Cloudflare est notre « nuage orange » : orange, en forme de nuage. Une plaisanterie, pas un diagnostic ni un partenariat.",
    fixed: "Votre domaine + Cloudflare Tunnel", fixedBody: "Pour une adresse stable, utilisez un domaine existant ou choisissez votre registraire. Le tunnel le relie au service MCP local ; un domaine n’est pas un serveur.",
    temporary: "Adresse temporaire", temporaryBody: "Pour essayer, après vérification de compatibilité. Quick Tunnels ne prend pas en charge SSE et n’a pas de SLA de production ; tous les transports MCP ne conviennent pas.",
    vps: "VPS + HTTPS", vpsBody: "Autre possibilité : héberger ou relayer MCP sur un VPS avec TLS, authentification et accès limités. Cela demande davantage de maintenance.", routeStatus: "Guide uniquement · Installation à intégrer", routeDocs: "Documentation Cloudflare",
    tunnelRepair: "Vérifiez le domaine, le DNS, le tunnel et le service cible. Un délai dépassé ne prouve pas une panne de Cloudflare.", authRepair: "Vérifiez la session et l’autorisation du connecteur. Ne partagez aucun secret dans le diagnostic.", localRepair: "Vérifiez le service local, le port et les permissions.", unknownRepair: "Lisez l’erreur réelle avant de changer l’adresse, les identifiants ou de relancer la tâche.",
  },
  ja: {
    book: "月の書", connection: "接続", chapters: "本の章", leaf: "クラウドと手元をつなぐ一頁", title: "月の光を、ここへ。", intro: "月の弦をそっと弾くと、信号が頁を離れます。月からの返事を待ちましょう。", check: "接続を確認", sending: "月の弦が信号を届けています…", idle: "月は、待っています。",
    success: "月の女神があなたの祈りに応えました", successDetail: "接続のハンドシェイクに成功しました", failure: "月の女神はあなたの祈りに応えませんでした", timeoutDetail: "接続のハンドシェイクがタイムアウトしました", errorDetail: "接続の確認に失敗しました", localReady: "ローカルの確認は成功しました。リモートのハンドシェイクは未確認です。",
    dimmed: "月の光は薄れましたが、消えたわけではありません。", orange: "オレンジ色の雲。", repair: "修復の頁を開く", retry: "もう一度試す", configure: "接続設定", details: "診断の詳細", demo: "プレビュー · 結果は演出用で、実際の接続ではありません。", demoSuccess: "デモ：接続成功", demoTimeout: "デモ：オレンジ雲のタイムアウト",
    scope: "保存した AgentDock MCP 接続を確認します。ここでの成功だけでは Web 対話からツールを使える証拠にはなりません。内蔵ブラウザーでも確認してください。",
    routes: "月の光に、アドレスを。", routeIntro: "Cloudflare はオレンジ色で雲の形なので「オレンジ雲」。冗談であり、障害の診断や提携の意味ではありません。",
    fixed: "独自ドメイン + Cloudflare Tunnel", fixedBody: "安定したアドレスには既存ドメインを使うか、好きな登録業者で取得できます。トンネルでローカル MCP に接続します。ドメインだけではサーバーになりません。",
    temporary: "一時アドレス", temporaryBody: "試用向けですが互換性の確認が必要です。Quick Tunnels は SSE 非対応で、本番稼働の SLA もありません。すべての MCP 方式が動くとは限りません。",
    vps: "VPS + HTTPS", vpsBody: "VPS に MCP を配置または中継し、TLS、認証、アクセス範囲を設定する方法もあります。保守作業は増えます。", routeStatus: "説明のみ · インストール手順は未接続", routeDocs: "Cloudflare 公式ドキュメント",
    tunnelRepair: "ドメイン、DNS、トンネルと接続先を確認してください。タイムアウトだけでは Cloudflare の問題とは判断できません。", authRepair: "ログインとコネクタの認証を確認してください。診断に秘密情報を貼り付けないでください。", localRepair: "ローカルサービス、ポートと権限を確認してください。", unknownRepair: "アドレスや認証情報の変更、再実行の前に実際のエラーを確認してください。",
  },
  ru: {
    book: "Книга Луны", connection: "Соединение", chapters: "Главы книги", leaf: "Страница между облаком и домом", title: "Пусть лунный свет достигнет вас.", intro: "Коснитесь лунной струны. Сигнал покинет страницу, и мы подождём ответа.", check: "Проверить соединение", sending: "Лунная струна передаёт ваш сигнал…", idle: "Луна ждёт.",
    success: "Богиня Луны ответила на вашу молитву", successDetail: "Соединение успешно согласовано", failure: "Богиня Луны не ответила на вашу молитву", timeoutDetail: "Время ожидания согласования истекло", errorDetail: "Проверка соединения не удалась", localReady: "Локальные проверки пройдены; удалённое соединение ещё не подтверждено.",
    dimmed: "Лунный свет потускнел, но не исчез.", orange: "Оранжевое облако.", repair: "Открыть страницу исправления", retry: "Попробовать снова", configure: "Настройки соединения", details: "Диагностика", demo: "ПРОСМОТР · Результаты демонстрационные, без реального подключения.", demoSuccess: "Демо: успешное соединение", demoTimeout: "Демо: тайм-аут оранжевого облака",
    scope: "Проверяется сохранённое MCP-соединение AgentDock. Это не доказывает вызов инструментов из Web-диалога; проверьте другую сторону во встроенном браузере.",
    routes: "Адрес для лунного света", routeIntro: "Cloudflare — наше «оранжевое облако»: оранжевое и похоже на облако. Это шутка, а не диагноз или партнёрство.",
    fixed: "Ваш домен + Cloudflare Tunnel", fixedBody: "Для постоянного адреса используйте свой домен или выберите регистратора. Туннель ведёт к локальному MCP-сервису; домен сам по себе не сервер.",
    temporary: "Временный адрес", temporaryBody: "Для пробы, после проверки совместимости. Quick Tunnels не поддерживает SSE и не имеет производственного SLA; не все транспорты MCP будут работать.",
    vps: "VPS + HTTPS", vpsBody: "Можно разместить или проксировать MCP на VPS с TLS, аутентификацией и ограничениями доступа. Потребуется больше обслуживания.", routeStatus: "Только руководство · Установка ещё не подключена", routeDocs: "Документация Cloudflare",
    tunnelRepair: "Проверьте домен, DNS, туннель и целевой сервис. Тайм-аут сам по себе не доказывает сбой Cloudflare.", authRepair: "Проверьте вход и авторизацию коннектора. Не вставляйте секреты в диагностику.", localRepair: "Проверьте локальный сервис, порт и разрешения.", unknownRepair: "Прочитайте настоящую ошибку перед сменой адреса, ключей или повтором задачи.",
  },
  de: {
    book: "Buch des Mondes", connection: "Verbindung", chapters: "Buchkapitel", leaf: "Eine Seite zwischen Cloud und Zuhause", title: "Möge das Mondlicht dich erreichen.", intro: "Zupfe die Mondsaite. Ein Signal verlässt diese Seite, und wir warten auf eine Antwort.", check: "Verbindung prüfen", sending: "Die Mondsaite trägt dein Signal…", idle: "Der Mond wartet.",
    success: "Die Mondgöttin hat dein Gebet erhört", successDetail: "Der Verbindungs-Handshake war erfolgreich", failure: "Die Mondgöttin hat dein Gebet nicht erhört", timeoutDetail: "Zeitüberschreitung beim Verbindungs-Handshake", errorDetail: "Die Verbindungsprüfung ist fehlgeschlagen", localReady: "Lokale Prüfung erfolgreich; der entfernte Handshake ist noch unbestätigt.",
    dimmed: "Das Mondlicht ist schwächer geworden, aber nicht verschwunden.", orange: "Eine orange Wolke.", repair: "Die Reparaturseite öffnen", retry: "Erneut versuchen", configure: "Verbindungseinstellungen", details: "Diagnosedetails", demo: "VORSCHAU · Demonstration, keine echte Verbindung.", demoSuccess: "Demo: erfolgreicher Handshake", demoTimeout: "Demo: Zeitüberschreitung der Wolke",
    scope: "Prüft deine gespeicherte AgentDock-MCP-Verbindung. Das beweist noch keinen Werkzeugaufruf aus dem Web-Chat; prüfe diese Seite im eingebauten Browser.",
    routes: "Eine Adresse für das Mondlicht", routeIntro: "Cloudflare ist unsere „orange Wolke“: orange und wolkenförmig. Ein Scherz, keine Diagnose oder Partnerschaft.",
    fixed: "Eigene Domain + Cloudflare Tunnel", fixedBody: "Für eine feste Adresse eine vorhandene Domain nutzen oder selbst einen Registrar wählen. Der Tunnel verbindet sie mit dem lokalen MCP-Dienst; eine Domain allein ist kein Server.",
    temporary: "Temporäre Adresse", temporaryBody: "Zum Ausprobieren nach Kompatibilitätsprüfung. Quick Tunnels unterstützt kein SSE und hat kein Produktions-SLA; nicht jeder MCP-Transport funktioniert.",
    vps: "VPS + HTTPS", vpsBody: "Alternativ MCP auf einem VPS betreiben oder weiterleiten, mit TLS, Authentifizierung und Zugriffslimits. Das erfordert mehr Wartung.", routeStatus: "Nur Anleitung · Installation noch nicht angebunden", routeDocs: "Cloudflare-Dokumentation",
    tunnelRepair: "Domain, DNS, Tunnel und Zieldienst prüfen. Eine Zeitüberschreitung allein beweist kein Cloudflare-Problem.", authRepair: "Anmeldung und Connector-Freigabe prüfen. Keine Geheimnisse in Diagnosen einfügen.", localRepair: "Lokalen Dienst, Port und Berechtigungen prüfen.", unknownRepair: "Vor Adress- oder Schlüsselwechsel und erneutem Ausführen erst den tatsächlichen Fehler prüfen.",
  },
};
