import type { Language } from "./types";
const en = {
  entry: "The Moon’s First Rise", entryHint: "Let an agent help with setup", title: "A Moonlit Letter", create: "Create the letter", copy: "Copy the letter", copied: "Copied", open: "Open local controls", stop: "Revoke access", close: "Close",
  consent: "Creating this letter allows your chosen local agent to check this launcher and advance its existing setup steps. A browser test can use one message of your account allowance. Sign-in, elevation and new permissions remain yours to approve.",
  secret: "The letter contains a short-lived local setup capability. Send it only to the agent you choose; do not post it publicly. Keep this launcher open.",
  preview: "Preview only: no server, real capability, account access or installation is created.", waiting: "Waiting for an agent to take over.",
  agentDock: "AgentDock · your MCP connection", url: "MCP URL for this computer", publicUrl: "Public HTTPS MCP URL for the web", save: "Save address", inspect: "Check handshake", login: "Authorize in browser", native2: "Web model tool-return channel (Native2)", guide: "How to configure your MCP address",
  intro: "AgentDock handles local orchestration. Native2 returns tools to the current web-model turn. They use separate channels and are not a completed bidirectional workflow merely because both are reachable.",
  addressHelp: "On this computer you may use http://127.0.0.1:8765/mcp. Web clients need your own reachable HTTPS /mcp address. With a domain or VPS, forward /mcp, /register, /oauth/* and /.well-known/*, and keep AgentDock’s server URL aligned. Authentication is required; a domain alone is not a server.",
  authHelp: "Use Codex-managed OAuth; enter the AgentDock authorization password only in the opened browser page. Star & Moon does not copy your browser cookies or ask for an OpenAI API key here.",
  registered: "Configuration saved in Star & Moon’s private MCP client. Your normal Codex configuration is unchanged.",
  webSetup: "Open ChatGPT connector settings in this app", copyAddress: "Copy public address", copiedAddress: "Public address copied",
  webStepOne: "Copy your public HTTPS address ending in /mcp.",
  webStepTwo: "In ChatGPT, create an AgentDock connector, choose OAuth, and approve access yourself on the authorization page.",
  webStepThree: "In that same ChatGPT conversation, ask it to call agentdock_context. Opening the page or passing a health check alone does not verify this tool call.",
  localLane: "Local → ChatGPT Web", webLane: "Web → local AgentDock", webNotVerified: "A tool call from ChatGPT to AgentDock has not yet been verified.", native2Back: "Back to connections",
};
export const assistanceCopy: Record<Language, { [K in keyof typeof en]: string }> = {
  en,
  "zh-CN": {
    entry: "明月初次升起", entryHint: "让代理协助安装", title: "月夜信", create: "生成月夜信", copy: "复制月夜信", copied: "已复制", open: "打开本地接管窗口", stop: "撤销接管授权", close: "关闭",
    consent: "生成这封信，将允许你选择的本地代理检查启动器，并推进现有安装步骤。浏览器测试可能使用一条消息的账号额度；登录、提权和新增权限仍由你本人确认。",
    secret: "信中含有限时本地接管权限。只交给你选择的代理，不要公开发布。请保持启动器开启。",
    preview: "仅预览：不会创建真实服务、接管密钥，不会登录或安装。", waiting: "等待代理接手。",
    agentDock: "AgentDock · 你的 MCP 连接", url: "供这台电脑使用的 MCP 地址", publicUrl: "供网页使用的公网 HTTPS MCP 地址", save: "保存地址", inspect: "检查握手", login: "在浏览器中授权", native2: "网页模型工具回传通道（Native2）", guide: "如何自己配置 MCP 地址",
    intro: "AgentDock 负责本地任务接入，Native2 负责当前网页模型回合的工具回传。两条通道相互独立，不能仅凭两端能访问就宣称双向工作流已经完成。",
    addressHelp: "本机可以使用 http://127.0.0.1:8765/mcp。网页客户端必须填写你自己的公网 HTTPS /mcp 地址。域名或 VPS 代理需要转发 /mcp、/register、/oauth/* 和 /.well-known/*，并让 AgentDock 的 server URL 与公网地址一致。必须保留认证；只有域名并不等于有了服务器。",
    authHelp: "使用 Codex 管理的 OAuth；只在打开的浏览器授权页输入 AgentDock 的授权密码。星月计划不复制日常浏览器 Cookie，也不在这里索取 OpenAI API key。",
    registered: "地址保存在星月计划独立的 MCP 客户端配置中，未修改你正常使用的 Codex 配置。",
    webSetup: "在应用内打开 ChatGPT 连接器设置", copyAddress: "复制公网地址", copiedAddress: "公网地址已复制",
    webStepOne: "复制你自己的公网 HTTPS 地址，地址应以 /mcp 结尾。",
    webStepTwo: "在 ChatGPT 新建 AgentDock 连接器，选择 OAuth，并在授权页由你本人确认授权。",
    webStepThree: "在同一段 ChatGPT 网页对话中，请它调用 agentdock_context。页面能打开或健康检查通过，都不能代替这次工具调用验证。",
    localLane: "本地 → ChatGPT 网页", webLane: "网页 → 本地 AgentDock", webNotVerified: "尚未验证 ChatGPT 网页对 AgentDock 的工具调用。", native2Back: "返回连接页",
  },
  "zh-Hant": {
    entry: "明月初次升起", entryHint: "讓代理協助安裝", title: "月夜信", create: "生成月夜信", copy: "複製月夜信", copied: "已複製", open: "開啟本機接管視窗", stop: "撤銷接管授權", close: "關閉",
    consent: "生成這封信，將允許你選擇的本機代理檢查啟動器，並推進現有安裝步驟。瀏覽器測試可能使用一條訊息的帳號額度；登入、提升權限和新增權限仍由你本人確認。",
    secret: "信中含有限時本機接管權限。只交給你選擇的代理，不要公開發佈。請保持啟動器開啟。",
    preview: "僅預覽：不會建立真實服務、接管金鑰，不會登入或安裝。", waiting: "等待代理接手。",
    agentDock: "AgentDock · 你的 MCP 連線", url: "供這台電腦使用的 MCP 地址", publicUrl: "供網頁使用的公網 HTTPS MCP 地址", save: "儲存地址", inspect: "檢查握手", login: "在瀏覽器中授權", native2: "網頁模型工具回傳通道（Native2）", guide: "如何自己設定 MCP 地址",
    intro: "AgentDock 負責本機任務接入，Native2 負責目前網頁模型回合的工具回傳。兩條通道相互獨立，不能僅憑兩端能存取就宣稱雙向工作流程已經完成。",
    addressHelp: "本機可以使用 http://127.0.0.1:8765/mcp。網頁用戶端必須填寫你自己的公網 HTTPS /mcp 地址。域名或 VPS 代理需要轉發 /mcp、/register、/oauth/* 和 /.well-known/*，並讓 AgentDock 的 server URL 與公網地址一致。必須保留認證；只有域名並不等於有了伺服器。",
    authHelp: "使用 Codex 管理的 OAuth；只在開啟的瀏覽器授權頁輸入 AgentDock 的授權密碼。星月計畫不複製日常瀏覽器 Cookie，也不在這裡索取 OpenAI API key。",
    registered: "地址儲存在星月計畫獨立的 MCP 用戶端設定中，未修改你正常使用的 Codex 設定。",
    webSetup: "在應用程式內開啟 ChatGPT 連接器設定", copyAddress: "複製公網地址", copiedAddress: "公網地址已複製",
    webStepOne: "複製你自己的公網 HTTPS 地址，地址應以 /mcp 結尾。",
    webStepTwo: "在 ChatGPT 新建 AgentDock 連接器，選擇 OAuth，並在授權頁由你本人確認授權。",
    webStepThree: "在同一段 ChatGPT 網頁對話中，請它呼叫 agentdock_context。頁面能開啟或健康檢查通過，都不能代替這次工具呼叫驗證。",
    localLane: "本機 → ChatGPT 網頁", webLane: "網頁 → 本機 AgentDock", webNotVerified: "尚未驗證 ChatGPT 網頁對 AgentDock 的工具呼叫。", native2Back: "返回連線頁",
  },
  fr: {
    entry: "Le premier lever de lune", entryHint: "Confier l’installation à un agent", title: "Une lettre au clair de lune", create: "Créer la lettre", copy: "Copier la lettre", copied: "Copié", open: "Ouvrir les contrôles locaux", stop: "Révoquer l’accès", close: "Fermer",
    consent: "Cette lettre autorise l’agent local choisi à vérifier le lanceur et à avancer dans son installation. Un test peut consommer un message. Connexion, élévation et nouvelles permissions restent à votre charge.", secret: "La lettre contient un accès local temporaire. Confiez-la uniquement à l’agent choisi, sans publication. Gardez le lanceur ouvert.", preview: "Aperçu : aucun serveur, secret, compte ou installation réels.", waiting: "En attente de l’agent.",
    agentDock: "AgentDock · votre connexion MCP", url: "URL MCP pour cet ordinateur", publicUrl: "URL MCP HTTPS publique pour le Web", save: "Enregistrer l’adresse", inspect: "Vérifier la connexion", login: "Autoriser dans le navigateur", native2: "Retour des outils du modèle Web (Native2)", guide: "Configurer votre adresse MCP",
    intro: "AgentDock gère l’accès aux tâches locales ; Native2 renvoie les outils du tour Web courant. Ces canaux restent distincts. Leur accessibilité ne prouve pas un flux bidirectionnel complet.", addressHelp: "En local : http://127.0.0.1:8765/mcp. Le Web exige votre URL HTTPS /mcp publique. Avec un domaine ou VPS, relayez /mcp, /register, /oauth/* et /.well-known/* et alignez l’URL serveur AgentDock. Gardez l’authentification ; un domaine n’est pas un serveur.", authHelp: "OAuth est géré par Codex. Saisissez le mot de passe AgentDock uniquement dans la page d’autorisation. Aucun Cookie personnel ni clé API OpenAI n’est demandé ici.", registered: "Adresse enregistrée dans le client MCP privé de Star & Moon ; votre configuration Codex habituelle reste inchangée.",
    webSetup: "Ouvrir les connecteurs ChatGPT dans cette application", copyAddress: "Copier l’adresse publique", copiedAddress: "Adresse publique copiée",
    webStepOne: "Copiez votre adresse HTTPS publique se terminant par /mcp.",
    webStepTwo: "Dans ChatGPT, créez un connecteur AgentDock, choisissez OAuth et confirmez vous-même l’accès sur la page d’autorisation.",
    webStepThree: "Dans cette même conversation ChatGPT, demandez l’appel de agentdock_context. Ouvrir la page ou réussir un contrôle de santé ne suffit pas à vérifier cet appel d’outil.",
    localLane: "Local → ChatGPT Web", webLane: "Web → AgentDock local", webNotVerified: "L’appel d’un outil AgentDock depuis ChatGPT n’a pas encore été vérifié.", native2Back: "Retour aux connexions",
  },
  ja: {
    entry: "月がはじめて昇るとき", entryHint: "エージェントに設定を手伝ってもらう", title: "月夜の手紙", create: "手紙を作成", copy: "手紙をコピー", copied: "コピーしました", open: "ローカル操作画面を開く", stop: "接管の許可を取り消す", close: "閉じる",
    consent: "選んだローカルエージェントに確認と既存の設定手順を許可する手紙です。テストはアカウントのメッセージ枠を使う場合があります。ログイン、権限昇格、新たな許可は本人が確認します。", secret: "手紙には期限付きのローカル操作権限が含まれます。選んだエージェント以外に公開せず、ランチャーを開いたままにしてください。", preview: "プレビューのみ：実際のサーバー、秘密情報、ログイン、インストールはありません。", waiting: "エージェントの接続を待っています。",
    agentDock: "AgentDock · MCP 接続", url: "この端末用の MCP URL", publicUrl: "Web 用の公開 HTTPS MCP URL", save: "アドレスを保存", inspect: "接続を確認", login: "ブラウザーで認証", native2: "Web モデルへのツール返却（Native2）", guide: "MCP アドレスの設定方法",
    intro: "AgentDock はローカルタスク、Native2 は現在の Web ターンのツール返却を担当します。別々の経路であり、疎通だけでは双方向の作業完了を証明しません。", addressHelp: "端末内では http://127.0.0.1:8765/mcp を利用できます。Web には自分の公開 HTTPS /mcp URL が必要です。ドメインや VPS では /mcp、/register、/oauth/*、/.well-known/* を転送し、AgentDock の server URL を一致させます。認証は必須で、ドメインだけではサーバーになりません。", authHelp: "OAuth は Codex が管理します。AgentDock のパスワードは開いた認証ページだけに入力してください。Cookie や OpenAI API キーは求めません。", registered: "Star & Moon 専用 MCP 設定に保存しました。通常の Codex 設定は変更していません。",
    webSetup: "アプリ内で ChatGPT のコネクタ設定を開く", copyAddress: "公開アドレスをコピー", copiedAddress: "公開アドレスをコピーしました",
    webStepOne: "/mcp で終わる、自分の公開 HTTPS アドレスをコピーしてください。",
    webStepTwo: "ChatGPT で AgentDock コネクタを作成し、OAuth を選びます。認証ページで本人がアクセスを許可してください。",
    webStepThree: "同じ ChatGPT の Web 会話で agentdock_context の呼び出しを依頼してください。ページが開くことやヘルスチェックの成功だけでは、このツール呼び出しを確認したことにはなりません。",
    localLane: "ローカル → ChatGPT Web", webLane: "Web → ローカルの AgentDock", webNotVerified: "ChatGPT から AgentDock へのツール呼び出しは、まだ確認されていません。", native2Back: "接続ページに戻る",
  },
  ru: {
    entry: "Первый восход Луны", entryHint: "Поручить настройку агенту", title: "Лунное письмо", create: "Создать письмо", copy: "Копировать письмо", copied: "Скопировано", open: "Открыть локальное управление", stop: "Отозвать доступ", close: "Закрыть",
    consent: "Письмо разрешает выбранному локальному агенту проверять программу и проходить её существующие шаги установки. Тест может использовать одно сообщение квоты. Вход, повышение прав и новые разрешения подтверждаете вы.", secret: "Письмо содержит временный локальный доступ. Передавайте его только выбранному агенту, не публикуйте. Оставьте программу открытой.", preview: "Только просмотр: без настоящего сервера, секрета, входа или установки.", waiting: "Ожидаем подключения агента.",
    agentDock: "AgentDock · ваше MCP-соединение", url: "MCP URL для этого компьютера", publicUrl: "Публичный HTTPS MCP URL для Web", save: "Сохранить адрес", inspect: "Проверить соединение", login: "Авторизовать в браузере", native2: "Возврат инструментов Web-модели (Native2)", guide: "Как настроить MCP-адрес",
    intro: "AgentDock принимает локальные задачи, Native2 возвращает инструменты текущему Web-ходу. Каналы независимы; доступность ещё не доказывает полный двусторонний процесс.", addressHelp: "Локально: http://127.0.0.1:8765/mcp. Для Web нужен ваш публичный HTTPS /mcp URL. Домен или VPS должен передавать /mcp, /register, /oauth/* и /.well-known/*; server URL AgentDock должен совпадать. Сохраняйте аутентификацию: домен не является сервером.", authHelp: "OAuth управляет Codex. Пароль AgentDock вводите только в открытой странице авторизации. Cookie и API-ключ OpenAI здесь не запрашиваются.", registered: "Адрес сохранён в отдельном MCP-клиенте Star & Moon; обычная конфигурация Codex не изменена.",
    webSetup: "Открыть настройки коннекторов ChatGPT в приложении", copyAddress: "Копировать публичный адрес", copiedAddress: "Публичный адрес скопирован",
    webStepOne: "Скопируйте свой публичный HTTPS-адрес, оканчивающийся на /mcp.",
    webStepTwo: "В ChatGPT создайте коннектор AgentDock, выберите OAuth и лично подтвердите доступ на странице авторизации.",
    webStepThree: "В том же веб-разговоре ChatGPT попросите вызвать agentdock_context. Открытие страницы или успешная проверка работоспособности сами по себе не подтверждают этот вызов инструмента.",
    localLane: "Локально → ChatGPT Web", webLane: "Web → локальный AgentDock", webNotVerified: "Вызов инструмента AgentDock из ChatGPT ещё не проверен.", native2Back: "Назад к подключениям",
  },
  de: {
    entry: "Der erste Mondaufgang", entryHint: "Ein Agent hilft bei der Einrichtung", title: "Ein Brief bei Mondschein", create: "Brief erstellen", copy: "Brief kopieren", copied: "Kopiert", open: "Lokale Steuerung öffnen", stop: "Zugriff widerrufen", close: "Schließen",
    consent: "Der Brief erlaubt dem gewählten lokalen Agenten, den Launcher zu prüfen und vorhandene Einrichtungsschritte auszuführen. Ein Test kann eine Nachricht verbrauchen. Anmeldung, Rechteerhöhung und neue Berechtigungen bestätigst du selbst.", secret: "Der Brief enthält zeitlich begrenzten lokalen Zugriff. Nur dem gewählten Agenten geben, nicht veröffentlichen. Den Launcher geöffnet lassen.", preview: "Nur Vorschau: kein echter Server, Schlüssel, Login oder Installation.", waiting: "Warten auf den Agenten.",
    agentDock: "AgentDock · deine MCP-Verbindung", url: "MCP-URL für diesen Computer", publicUrl: "Öffentliche HTTPS-MCP-URL für das Web", save: "Adresse speichern", inspect: "Handshake prüfen", login: "Im Browser autorisieren", native2: "Werkzeugrückgabe des Web-Modells (Native2)", guide: "Eine eigene MCP-Adresse einrichten",
    intro: "AgentDock nimmt lokale Aufgaben an, Native2 liefert Werkzeuge an den aktuellen Web-Durchlauf zurück. Die Kanäle bleiben getrennt; Erreichbarkeit allein beweist keinen vollständigen Ablauf.", addressHelp: "Lokal ist http://127.0.0.1:8765/mcp möglich. Das Web benötigt deine öffentliche HTTPS-/mcp-Adresse. Domain oder VPS müssen /mcp, /register, /oauth/* und /.well-known/* weiterleiten; die AgentDock-Server-URL muss übereinstimmen. Authentifizierung bleibt nötig; eine Domain allein ist kein Server.", authHelp: "Codex verwaltet OAuth. Das AgentDock-Passwort nur in der geöffneten Browserseite eingeben. Persönliche Cookies und OpenAI-API-Schlüssel werden hier nicht verlangt.", registered: "Adresse im privaten Star-&-Moon-MCP-Client gespeichert; deine normale Codex-Konfiguration bleibt unverändert.",
    webSetup: "ChatGPT-Connector-Einstellungen in dieser App öffnen", copyAddress: "Öffentliche Adresse kopieren", copiedAddress: "Öffentliche Adresse kopiert",
    webStepOne: "Kopiere deine öffentliche HTTPS-Adresse, die auf /mcp endet.",
    webStepTwo: "Erstelle in ChatGPT einen AgentDock-Connector, wähle OAuth und bestätige den Zugriff selbst auf der Freigabeseite.",
    webStepThree: "Bitte ChatGPT im selben Web-Gespräch, agentdock_context aufzurufen. Eine geöffnete Seite oder ein erfolgreicher Zustandscheck allein bestätigt diesen Werkzeugaufruf nicht.",
    localLane: "Lokal → ChatGPT Web", webLane: "Web → lokaler AgentDock", webNotVerified: "Ein AgentDock-Werkzeugaufruf aus ChatGPT wurde noch nicht bestätigt.", native2Back: "Zurück zu den Verbindungen",
  },
};

export const assistanceStateCopy: Record<Language, Record<string, string>> = {
  en: {
    unconfigured: "Add an address to begin", configured: "Address saved", checking: "Checking the connection…",
    "invalid-config": "Please check the address", "auth-required": "Your authorization is needed", authorizing: "Waiting for you to authorize",
    authorized: "Authorization complete", connected: "The connection responded", unverified: "Not yet verified", timeout: "No response in time — try again", error: "This step needs attention",
    "preview-only": "Preview only — no real connection", revoked: "Access revoked", expired: "Access expired", reviewRequired: "Please review and confirm",
  },
  "zh-CN": {
    unconfigured: "先添加一个地址", configured: "地址已保存", checking: "正在检查连接…",
    "invalid-config": "请检查地址", "auth-required": "需要你本人授权", authorizing: "等待你完成授权",
    authorized: "授权已完成", connected: "连接已响应", unverified: "尚未验证", timeout: "等待超时，请重试", error: "这一步需要检查",
    "preview-only": "仅预览，未建立真实连接", revoked: "授权已撤销", expired: "授权已过期", reviewRequired: "请查看并确认",
  },
  "zh-Hant": {
    unconfigured: "先新增一個地址", configured: "地址已儲存", checking: "正在檢查連線…",
    "invalid-config": "請檢查地址", "auth-required": "需要你本人授權", authorizing: "等待你完成授權",
    authorized: "授權已完成", connected: "連線已回應", unverified: "尚未驗證", timeout: "等待超時，請重試", error: "這一步需要檢查",
    "preview-only": "僅預覽，未建立真實連線", revoked: "授權已撤銷", expired: "授權已過期", reviewRequired: "請查看並確認",
  },
  fr: {
    unconfigured: "Ajoutez une adresse pour commencer", configured: "Adresse enregistrée", checking: "Vérification de la connexion…",
    "invalid-config": "Vérifiez l’adresse", "auth-required": "Votre autorisation est nécessaire", authorizing: "En attente de votre autorisation",
    authorized: "Autorisation terminée", connected: "La connexion a répondu", unverified: "Pas encore vérifié", timeout: "Délai dépassé — réessayez", error: "Cette étape nécessite une vérification",
    "preview-only": "Aperçu uniquement — aucune connexion réelle", revoked: "Accès révoqué", expired: "Accès expiré", reviewRequired: "Veuillez vérifier et confirmer",
  },
  ja: {
    unconfigured: "まずアドレスを追加", configured: "アドレスを保存しました", checking: "接続を確認中…",
    "invalid-config": "アドレスを確認してください", "auth-required": "本人の許可が必要です", authorizing: "あなたの許可を待っています",
    authorized: "認証が完了しました", connected: "接続先から応答がありました", unverified: "まだ確認されていません", timeout: "応答待ちがタイムアウトしました。再試行してください", error: "この手順を確認してください",
    "preview-only": "プレビューのみ — 実際の接続はありません", revoked: "許可を取り消しました", expired: "許可の期限が切れました", reviewRequired: "内容を確認して承認してください",
  },
  ru: {
    unconfigured: "Сначала добавьте адрес", configured: "Адрес сохранён", checking: "Проверяем подключение…",
    "invalid-config": "Проверьте адрес", "auth-required": "Нужно ваше разрешение", authorizing: "Ждём вашего разрешения",
    authorized: "Авторизация завершена", connected: "Подключение ответило", unverified: "Ещё не проверено", timeout: "Время ожидания вышло — повторите", error: "Этот шаг требует проверки",
    "preview-only": "Только просмотр — без настоящего подключения", revoked: "Доступ отозван", expired: "Срок доступа истёк", reviewRequired: "Проверьте и подтвердите",
  },
  de: {
    unconfigured: "Füge zuerst eine Adresse hinzu", configured: "Adresse gespeichert", checking: "Verbindung wird geprüft…",
    "invalid-config": "Bitte prüfe die Adresse", "auth-required": "Deine Freigabe ist nötig", authorizing: "Warten auf deine Freigabe",
    authorized: "Freigabe abgeschlossen", connected: "Die Verbindung hat geantwortet", unverified: "Noch nicht geprüft", timeout: "Wartezeit abgelaufen — erneut versuchen", error: "Dieser Schritt muss geprüft werden",
    "preview-only": "Nur Vorschau — keine echte Verbindung", revoked: "Zugriff widerrufen", expired: "Zugriff abgelaufen", reviewRequired: "Bitte prüfen und bestätigen",
  },
};
