import type { Language } from "./types";

const en = { title: "Recovery and debugging", check: "Run diagnostics", export: "Export redacted logs", debug: "Open local developer tools", rollback: "Restore previous Codex connection", hint: "Back only changes the page. Retry keeps saved progress; failed setup restores its checkpoint. Diagnostics do not install anything or send a model request. Developer tools are powerful: do not paste untrusted code.", hook: "An older bridge hook conflicts with this setup. Retry uses the verified, reversible migration; unrecognized or modified hooks require manual review.", port: "Another program owns the port. New installations select a free loopback port; existing installations keep their saved port.", done: "Diagnostics completed. Setup is still unverified.", failed: "Diagnostics could not complete:" };
type RecoveryCopy = { [K in keyof typeof en]: string };
export const setupRecoveryCopy: Record<Language, RecoveryCopy> = {
  en,
  "zh-CN": { title: "恢复与调试", check: "运行诊断", export: "导出脱敏日志", debug: "打开本地调试工具", rollback: "恢复原 Codex 连接", hint: "返回只切换页面，不清空进度；失败的安装会恢复检查点，可修复后重试。诊断不安装、不发送模型请求。调试工具有修改能力，请勿粘贴不可信代码。", hook: "检测到旧网页桥的中断钩子冲突。重试会核验并可撤销地迁移已知钩子；无法确认或已被修改的内容仍需人工检查。", port: "端口被其他程序占用。首次安装会选择空闲的本地端口；已有安装保留原端口。", done: "诊断完成，尚未把安装标记为成功。", failed: "诊断未完成：" },
  "zh-Hant": { title: "恢復與偵錯", check: "執行診斷", export: "匯出去識別日誌", debug: "開啟本機偵錯工具", rollback: "恢復原 Codex 連線", hint: "返回只切換頁面，不清空進度；失敗的安裝會恢復檢查點，可修復後重試。診斷不安裝、不傳送模型請求。偵錯工具可修改內容，請勿貼上不可信程式碼。", hook: "偵測到舊網頁橋接器的中斷鉤子衝突。重試會核驗並可撤銷地遷移已知鉤子；無法確認或已修改的內容仍需人工檢查。", port: "連接埠已被佔用。首次安裝會選擇空閒本機連接埠；已有安裝保留原設定。", done: "診斷完成，尚未將安裝標記為成功。", failed: "診斷未完成：" },
  fr: { title: "Récupération et débogage", check: "Lancer le diagnostic", export: "Exporter les journaux expurgés", debug: "Ouvrir les outils locaux", rollback: "Restaurer la connexion Codex précédente", hint: "Retour conserve la progression. Un échec restaure le point de contrôle. Le diagnostic n’installe rien et n’envoie aucune requête de modèle. Ne collez pas de code non fiable dans les outils.", hook: "Conflit avec un ancien hook. Réessayez pour une migration vérifiée et réversible ; les modifications inconnues exigent un examen manuel.", port: "Port occupé. Une nouvelle installation choisit un port local libre ; une installation existante conserve le sien.", done: "Diagnostic terminé ; installation non validée.", failed: "Diagnostic incomplet :" },
  ja: { title: "復旧とデバッグ", check: "診断を実行", export: "機密情報を除いたログを保存", debug: "ローカル開発ツールを開く", rollback: "元の Codex 接続を復元", hint: "戻る操作は進捗を消しません。失敗した設定はチェックポイントを復元します。診断はインストールやモデル呼び出しを行いません。開発ツールに信頼できないコードを貼らないでください。", hook: "以前のフックと競合しています。再試行では検証済みのフックだけを元に戻せる形で移行します。不明な変更は手動確認が必要です。", port: "ポートが使用中です。初回設定は空きローカルポートを選び、既存設定は保存済みポートを保持します。", done: "診断完了。設定はまだ検証されていません。", failed: "診断未完了：" },
  ru: { title: "Восстановление и отладка", check: "Запустить диагностику", export: "Экспорт обезличенных журналов", debug: "Открыть локальные инструменты", rollback: "Восстановить прежнее подключение Codex", hint: "Назад сохраняет прогресс. При сбое настройки восстанавливается контрольная точка. Диагностика ничего не устанавливает и не вызывает модель. Не вставляйте недоверенный код в инструменты.", hook: "Конфликт со старым хуком. Повтор проверит и обратимо перенесёт известный хук; неизвестные изменения требуют ручной проверки.", port: "Порт занят. Новая установка выбирает свободный локальный порт; существующая сохраняет свой.", done: "Диагностика завершена; установка ещё не подтверждена.", failed: "Диагностика не завершена:" },
  de: { title: "Wiederherstellung und Debugging", check: "Diagnose ausführen", export: "Bereinigte Protokolle exportieren", debug: "Lokale Entwicklertools öffnen", rollback: "Vorherige Codex-Verbindung wiederherstellen", hint: "Zurück erhält den Fortschritt. Bei einem Einrichtungsfehler wird der Prüfpunkt wiederhergestellt. Die Diagnose installiert nichts und ruft kein Modell auf. Fügen Sie keinen unvertrauenswürdigen Code in die Tools ein.", hook: "Konflikt mit einem älteren Hook. Erneutes Versuchen migriert nur geprüfte Hooks reversibel; unbekannte Änderungen erfordern eine manuelle Prüfung.", port: "Port belegt. Neue Installationen wählen einen freien lokalen Port; bestehende behalten ihren Port.", done: "Diagnose abgeschlossen; Einrichtung noch nicht bestätigt.", failed: "Diagnose unvollständig:" },
};

export function setupFailureHint(failure: string | null, language: Language): string | null {
  if (!failure) return null;
  if (/interrupt hook|interrupt lifecycle hook/i.test(failure)) return setupRecoveryCopy[language].hook;
  if (/EADDRINUSE|Cannot bind|port.*occupied/i.test(failure)) return setupRecoveryCopy[language].port;
  return null;
}
