import type { Language } from "./types";

const en = {
  title: "When should Star Moon stay with you?",
  intro: "Both options are off for new installations. Keep your current choices or turn either on yourself; you can change them later in Settings.",
  login: "Start after I sign in to this computer",
  loginBody: "Starts in your user session after login, not as a system service before login.",
  keepRunning: "Keep running when I close the window",
  keepRunningBody: "Stays in the tray after closing the window. Without a tray, closing quits. Use Quit to stop the app.",
  separateTitle: "Separate choices for remote access",
  separateBody: "Remote debugging and public web access need separate permission. These options do not enable them; future controls will ask you explicitly.",
  preview: "Preview only: these switches change this page, not startup, background tasks or saved settings.",
  saving: "Saving your choice…", saved: "Your choice is saved.",
  failed: "The change was not confirmed. Check the details and try again.",
  unsupported: "This system or build does not support setting login startup. The requested change was not confirmed.",
  details: "View details",
};

export const startupCopy: Record<Language, { [K in keyof typeof en]: string }> = {
  en,
  "zh-CN": {
    title: "你希望星月何时陪伴？",
    intro: "新安装时，两项默认关闭。你可以保留当前选择，也可以亲自开启，之后仍能在设置中更改。",
    login: "登录这台电脑后自动启动",
    loginBody: "在你登录后的用户会话中启动，不是登录前就运行的系统服务。",
    keepRunning: "关闭窗口后继续运行",
    keepRunningBody: "关闭窗口后留在托盘运行；没有可用托盘时会退出。选择“退出”可结束应用。",
    separateTitle: "远程访问需要另行选择",
    separateBody: "远程调试和对外网页访问需要单独授权，不会随这两项一起开启；未来提供相关开关时，会另行征得同意。",
    preview: "仅预览：开关只改变本页展示，不更改系统启动、后台任务或已保存设置。",
    saving: "正在保存选择…", saved: "选择已保存。",
    failed: "这次更改未被确认，请查看详情后重试。",
    unsupported: "当前系统或版本不支持设置登录启动，这次更改未被确认。",
    details: "查看详情",
  },
  "zh-Hant": {
    title: "你希望星月何時陪伴？",
    intro: "新安裝時，兩項預設關閉。你可以保留目前選擇，也可以親自開啟，之後仍能在設定中變更。",
    login: "登入這台電腦後自動啟動",
    loginBody: "在你登入後的使用者工作階段中啟動，不是登入前就執行的系統服務。",
    keepRunning: "關閉視窗後繼續執行",
    keepRunningBody: "關閉視窗後留在系統匣執行；沒有可用系統匣時會結束。選擇「結束」可關閉應用程式。",
    separateTitle: "遠端存取需要另行選擇",
    separateBody: "遠端偵錯和對外網頁存取需要單獨授權，不會隨這兩項一起開啟；未來提供相關開關時，會另行徵得同意。",
    preview: "僅預覽：開關只改變本頁顯示，不變更系統啟動、背景工作或已儲存設定。",
    saving: "正在儲存選擇…", saved: "選擇已儲存。",
    failed: "這次變更未經確認，請查看詳細資訊後重試。",
    unsupported: "目前系統或版本不支援設定登入啟動，這次變更未經確認。",
    details: "查看詳細資訊",
  },
  fr: {
    title: "Quand Star Moon doit-il vous accompagner ?",
    intro: "Les deux options sont désactivées à la première installation. Gardez vos choix ou activez-les vous-même ; vous pourrez les modifier dans les paramètres.",
    login: "Démarrer après ma connexion à cet ordinateur",
    loginBody: "Démarre dans votre session après la connexion, pas comme un service système avant celle-ci.",
    keepRunning: "Continuer après la fermeture de la fenêtre",
    keepRunningBody: "Reste dans la zone de notification. Sans cette zone, fermer la fenêtre quitte l’application. Choisissez Quitter pour l’arrêter.",
    separateTitle: "Choix distincts pour l’accès à distance",
    separateBody: "Le débogage à distance et l’accès Web public nécessitent une autorisation distincte. Ces options ne les activent pas ; toute future commande demandera votre accord.",
    preview: "Aperçu uniquement : ces interrupteurs changent la page, pas le démarrage, les tâches de fond ou les réglages enregistrés.",
    saving: "Enregistrement de votre choix…", saved: "Votre choix est enregistré.",
    failed: "La modification n’a pas été confirmée. Consultez les détails et réessayez.",
    unsupported: "Ce système ou cette version ne permet pas de régler le démarrage à la connexion. La modification n’a pas été confirmée.",
    details: "Voir les détails",
  },
  ja: {
    title: "星月を、いつそばに置きますか。",
    intro: "新規インストールでは両方とも無効です。現在の設定を保つか、自分で有効にできます。後から設定で変更できます。",
    login: "この端末へのログイン後に起動する",
    loginBody: "ログイン後のユーザーセッションで起動します。ログイン前から動くシステムサービスではありません。",
    keepRunning: "ウィンドウを閉じても実行を続ける",
    keepRunningBody: "閉じた後はトレイに常駐します。トレイが使えない場合は終了します。アプリを止めるには「終了」を選んでください。",
    separateTitle: "リモートアクセスは別途選択",
    separateBody: "リモートデバッグや Web への公開には別の許可が必要です。この 2 項目では有効になりません。将来の機能でも改めて同意を確認します。",
    preview: "プレビューのみです。スイッチは画面だけを変え、起動設定、バックグラウンド処理、保存済み設定は変更しません。",
    saving: "選択を保存中…", saved: "選択を保存しました。",
    failed: "変更を確認できませんでした。詳細を確認して再試行してください。",
    unsupported: "このシステムまたはバージョンではログイン時の起動を設定できません。変更は確認されていません。",
    details: "詳細を表示",
  },
  ru: {
    title: "Когда Star Moon должен быть рядом?",
    intro: "При первой установке обе опции выключены. Сохраните текущий выбор или включите их сами. Позже это можно изменить в настройках.",
    login: "Запускать после моего входа в компьютер",
    loginBody: "Запускается в вашей сессии после входа, а не как системная служба до входа.",
    keepRunning: "Продолжать работу после закрытия окна",
    keepRunningBody: "Остаётся в системном трее. Если трей недоступен, закрытие окна завершает приложение. Для остановки выберите «Выход».",
    separateTitle: "Отдельный выбор для удалённого доступа",
    separateBody: "Удалённая отладка и публичный веб-доступ требуют отдельного разрешения. Эти опции их не включают; будущие элементы управления запросят ваше согласие.",
    preview: "Только просмотр: переключатели меняют страницу, а не автозапуск, фоновые задачи или сохранённые настройки.",
    saving: "Сохраняем ваш выбор…", saved: "Ваш выбор сохранён.",
    failed: "Изменение не подтверждено. Проверьте подробности и повторите попытку.",
    unsupported: "Эта система или сборка не поддерживает настройку запуска при входе. Изменение не подтверждено.",
    details: "Посмотреть подробности",
  },
  de: {
    title: "Wann soll Star Moon für dich da sein?",
    intro: "Bei einer neuen Installation sind beide Optionen aus. Behalte deine Auswahl oder aktiviere sie selbst. Du kannst sie später in den Einstellungen ändern.",
    login: "Nach meiner Anmeldung am Computer starten",
    loginBody: "Startet nach der Anmeldung in deiner Benutzersitzung, nicht als Systemdienst vor der Anmeldung.",
    keepRunning: "Nach dem Schließen des Fensters weiterlaufen",
    keepRunningBody: "Läuft im Infobereich weiter. Ohne Infobereich beendet das Schließen die App. Wähle Beenden, um sie zu stoppen.",
    separateTitle: "Fernzugriff erfordert eine eigene Auswahl",
    separateBody: "Remote-Debugging und öffentlicher Webzugriff brauchen eine separate Freigabe. Diese Optionen aktivieren beides nicht; künftige Schalter fragen ausdrücklich nach.",
    preview: "Nur Vorschau: Die Schalter ändern diese Seite, nicht den Systemstart, Hintergrundaufgaben oder gespeicherte Einstellungen.",
    saving: "Deine Auswahl wird gespeichert…", saved: "Deine Auswahl ist gespeichert.",
    failed: "Die Änderung wurde nicht bestätigt. Prüfe die Details und versuche es erneut.",
    unsupported: "Dieses System oder diese Version unterstützt die Einstellung des Anmeldestarts nicht. Die Änderung wurde nicht bestätigt.",
    details: "Details ansehen",
  },
};
